/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],
    _STYLE_: [
        '符号', '待归类', '地图', '防具', '武器', '道具', '属性', '敌人'
    ],

    //1.0.符号
    '': '',
    //建筑开始
    'Cursor': '游标',
    'cursors': '游标',
    'Grandma': '老奶奶',
    'Farm': '农场',
    'Mine': '矿山',
    'Factory': '工厂',
    'Bank': '银行',
    'Temple': '寺庙',
    'Wizard tower': '精灵塔',
    'Shipment': '装船',
    'Alchemy lab': '炼金实验室',
    'Portal': '传送门',
    'Time machine': '时光机器',
    'Antimatter condenser': '反物质冷凝器',
    'Prism': '棱镜',
    'Chancemaker': '机会制造商',
    'Fractal engine': '分形引擎',
    //建筑结束
    //Tag开始
    'Upgrade': '升级',
    'Locked': '未解锁',
    'Achievement': '成就',
    'Unlocked': '已解锁',
    'Purchased': '已购买',
    'Cookie': '饼干',
    'Heavenly': '天堂',
    'Switch': '可切换',
    'Tech': '科技',
    //Tag结束
    'clicked': '点击',
    'baked': '烘烤',
    'harvested': '收获',
    'mined': '开采',
    //升级名称开始
    'Reinforced index finger': '加强的食指',
    'Carpal tunnel prevention cream': '腕管预防霜',
    'Ambidextrous': '双手通用',
    'Thousand fingers': '千手指',
    'Million fingers': '百万手指',
    'Billion fingers': '十亿手指',
    'Trillion fingers': '万亿手指',
    'Forwards from grandma': '前锋老奶奶',
    'Steel-plated rolling pins': '钢包滚针',
    'Lubricated dentures': '润滑假牙',
    'Cheap hoes': '廉价的锄头',
    'Fertilizer': '肥料',
    'Cookie trees': '饼干树',
    'Sturdier conveyor belts': '更坚固的传送带',
    'Child labor': '童工',
    'Sweatshop': '血汗工厂',
    'Sugar gas': '糖气',
    'Megadrill': '大型钻',
    'Ultradrill': '超级钻',
    'Vanilla nebulae': '香草星云',
    'Wormholes': '虫洞',
    'Frequent flyer': '飞行常客',
    'Antimony': '锑',
    'Essence of dough': '面团的本质',
    'True chocolate': '原味巧克力',
    'Ancient tablet': '古碑文',
    'Insane oatling workers': '疯狂的燕麦工人',
    'Soul bond': '灵魂纽带',
    'Flux capacitors': '通量电容器',
    'Time paradox resolver': '时间悖论解析器',
    'Quantum conundrum': '量子难题',
    'Kitten helpers': '小猫助手',
    'Kitten workers': '小猫工人',
    'Plain cookies': '原味饼干',
    'Sugar cookies': '糖饼干',
    'Oatmeal raisin cookies': '燕麦葡萄干饼干',
    'Peanut butter cookies': '花生酱饼干',
    'Coconut cookies': '椰子饼干',
    'White chocolate cookies': '白巧克力饼干',
    'Macadamia nut cookies': '坚果饼干',
    'Double-chip cookies': '双层饼干',
    'White chocolate macadamia nut cookies': '白巧克力坚果饼干',
    'All-chocolate cookies': '全巧克力饼干',
    'Prune juice': '西梅汁',
    'Genetically-modified cookies': '转基因饼干',
    'Radium reactors': '镭反应堆',
    'Ultimadrill': '天涯钻',
    'Warp drive': '曲速驱动',
    'Ambrosia': '美味食物',
    'Sanity dance': '理智之舞',
    'Causality enforcer': '因果关系的执行者',
    'Lucky day': '幸运日',
    'Serendipity': '意外的惊喜',
    'Kitten engineers': '小猫工程师',
    'Dark chocolate-coated cookies': '黑巧克力饼干',
    'White chocolate-coated cookies': '白巧克力饼干',
    'Farmer grandmas': '农民老奶奶',
    'Miner grandmas': '矿工老奶奶',
    'Worker grandmas': '工人老奶奶',
    'Cosmic grandmas': '宇宙老奶奶',
    'Transmuted grandmas': '嬗变老奶奶',
    'Altered grandmas': '改造老奶奶',
    "Grandmas\' grandmas": '老奶奶的奶奶',
    'Specialized chocolate chips': '专业巧克力片',
    'Designer cocoa beans': '可可豆设计师',
    'Ritual rolling pins': '仪式滚针',
    'Underworld ovens': '地下烤箱',
    'One mind': '同心协力',
    'Exotic nuts': '奇异果',
    'Communal brainsweep': '集体洗脑',
    'Arcane sugar': '神秘的糖',
    'Elder Pact': '长者盟约',
    'Elder Pledge': '老人的承诺',
    'Plastic mouse': '塑料鼠标',
    'Iron mouse': '铁制鼠标',
    'Titanium mouse': '钛制鼠标',
    'Adamantium mouse': '釉质鼠标',
    'Ultrascience': '超音波',
    'Eclipse cookies': '日食饼干',
    'Zebra cookies': '斑马饼干',
    'Snickerdoodles': '肉桂奶油饼干',
    'Stroopwafels': '荷式松饼干',
    'Macaroons': '蛋白杏仁饼干',
    'Neuromancy': '神经占卜',
    'Sacrificial rolling pins': '牺牲擀面杖',
    'Get lucky': '走运',
    'Revoke Elder Covenant': '撤销老人契约',
    'Elder Covenant': '老人契约',
    'Gold hoard': '黄金储备',
    'Empire biscuits': '帝国饼干',
    'British tea biscuits': '英国茶饼干',
    'Chocolate british tea biscuits': '英国茶巧克力饼干',
    'Round british tea biscuits': '圆形英国茶饼干',
    'Round chocolate british tea biscuits': '圆巧克力英国茶饼干',
    'Round british tea biscuits with heart motif': '有心形图案的圆形英国茶饼干',
    'Round chocolate british tea biscuits with heart motif': '有心形图案的圆巧克力英国茶饼干',
    'Sugar bosons': '糖玻色子',
    'String theory': '弦理论',
    'Large macaron collider': '大马卡龙对撞机',
    'Big bang bake': '大爆炸烘烤',
    'Antigrandmas': '反物质奶奶',
    'Madeleines': '玛德琳蛋糕',
    'Palmiers': '蝴蝶酥',
    'Palets': '托盘',
    'Sabl&eacute;s': '沙琪玛饼干',
    'Kitten overseers': '小猫监工',
    'Sextillion fingers': '百万的六乘方手指',
    'Double-thick glasses': '双层厚眼镜',
    'Gingerbread scarecrows': '姜饼稻草人',
    'Recombobulators': '重新组合',
    'H-bomb mining': '氢弹开采',
    'Chocolate monoliths': '巧克力块',
    'Aqua crustulae': '甲壳纲',
    'Brane transplant': '膜移植',
    'Yestermorrow comparators': '昨天比较器',
    'Reverse cyclotrons': '反向回旋加速器',
    'Unobtainium mouse': '难得素鼠标',
    'Caramoas': '卡拉恐鸟',
    'Sagalongs': '萨松',
    'Shortfoils': '短管',
    'Win mints': '赢得薄荷糖',
    'Perfect idling': '完美的空转',
    'Fig gluttons': '无花果胶子',
    'Jaffa cakes': '佳发蛋糕',
    "Grease\'s cups": '油脂杯',
    'Loreols': '洛丽醇',
    'Heavenly chip secret': '天堂芯片的秘密',
    'Heavenly cookie stand': '天堂饼干站',
    'Heavenly bakery': '天堂面包店',
    'Heavenly confectionery': '天堂糖果店',
    'Heavenly key': '天堂钥匙',
    'Skull cookies': '骷髅饼干',
    'Ghost cookies': '幽灵饼干',
    'Bat cookies': '蝙蝠饼干',
    'Slime cookies': '粘液饼干',
    'Pumpkin cookies': '南瓜饼干',
    'Eyeball cookies': '眼球饼干',
    'Spider cookies': '蜘蛛饼干',
    'Wrinkler doormat': '皱纹门垫',
    'Persistent memory': '持久的记忆',
    'Christmas tree biscuits': '圣诞树饼干',
    'Snowflake biscuits': '雪花饼干',
    'Snowman biscuits': '雪人饼干',
    'Holly biscuits': '冬青饼干',
    'Candy cane biscuits': '糖果手杖饼干',
    'Bell biscuits': '铃铛饼干',
    'Present biscuits': '礼品饼干',
    'Gingerbread men': '姜饼人',
    'Gingerbread trees': '姜饼树',
    'A festive hat': '节庆帽子',
    'Increased merriness': '增加愉快',
    'Improved jolliness': '改良愉快',
    'A lump of coal': '一堆煤',
    'An itchy sweater': '发痒的毛衣',
    'Reindeer baking grounds': '驯鹿烘烤场',
    'Weighted sleighs': '加重雪橇',
    'Ho ho ho-flavored frosting': '何蚝味糖霜',
    'Season savings': '季节储蓄',
    'Toy workshop': '玩具车间',
    'Naughty list': '淘气名单',
    "Santa\'s bottomless bag": '圣诞老人的无底包',
    "Santa\'s helpers": '圣诞老人的助手',
    "Santa\'s legacy": '圣诞老人的遗物',
    "Santa\'s milk and cookies": '圣诞老人的牛奶和饼干',
    "Santa\'s dominion": '圣诞老人的统治',
    'Reindeer season': '驯鹿的季节',
    'Pure heart biscuits': '纯心饼干',
    'Ardent heart biscuits': '心切饼干',
    'Sour heart biscuits': '酸心饼干',
    'Weeping heart biscuits': '心水饼干',
    'Golden heart biscuits': '金心饼干',
    'Eternal heart biscuits': '永恒的心饼干',
    'Gem polish': '宝石抛光',
    '9th color': '9号颜色',
    'Chocolate light': '巧克力之光',
    'Grainbow': '谷粒弓',
    'Pure cosmic light': '纯粹的宇宙之光',
    'Rainbow grandmas': '彩虹老奶奶',
    'Season switcher': '季节切换器',
    'Festive biscuit': '节日饼干',
    'Ghostly biscuit': '幽灵饼干',
    'Lovesick biscuit': '相思病饼干',
    'Fool\'s biscuit': '傻瓜的饼干',
    'Eternal seasons': '永恒的季节',
    'Kitten managers': '小猫经理',
    'Septillion fingers': '巨量的手指',
    'Octillion fingers': '千的九次方手指',
    'Eludium mouse': 'E合金鼠标',
    'Wishalloy mouse': '叉合金鼠标',
    'Aging agents': '老化剂',
    'Pulsar sprinklers': '脉冲星洒水器',
    'Deep-bake process': '深度烘焙过程',
    'Coreforge': '铁匠铺',
    'Generation ship': '发电船',
    'Origin crucible': '起源坩埚',
    'Deity-sized portals': '大型传送门',
    'Far future enactment': '未来的法令',
    'Nanocosmics': '纳米宇宙',
    'Glow-in-the-dark': '在黑暗中发光',
    'Rose macarons': '玫瑰马卡龙',
    'Lemon macarons': '柠檬马卡龙',
    'Chocolate macarons': '巧克力马卡龙',
    'Pistachio macarons': '开心果马卡龙',
    'Hazelnut macarons': '榛子马卡龙',
    'Violet macarons': '紫罗兰马卡龙',
    'Magic shenanigans': '神奇的恶作剧',
    'Bunny biscuit': '兔子饼干',
    'Chicken egg': '鸡蛋',
    'Duck egg': '鸭蛋',
    'Turkey egg': '火鸡蛋',
    'Quail egg': '鹌鹑蛋',
    'Robin egg': '知更鸟蛋',
    'Ostrich egg': '鸵鸟蛋',
    'Cassowary egg': '食火鸡蛋',
    'Salmon roe': '鲑鱼籽',
    'Frogspawn': '蛙卵',
    'Shark egg': '鲨鱼卵',
    'Turtle egg': '龟蛋',
    'Ant larva': '蚂蚁幼虫',
    'Golden goose egg': '金鹅蛋',
    'Faberge egg': '法贝热彩蛋',
    'Wrinklerspawn': '皱纹卵',
    'Cookie egg': '饼干蛋',
    'Omelette': '煎蛋',
    'Chocolate egg': '巧克力蛋',
    'Century egg': '世纪蛋',
    '"egg"': '"蛋"',
    'Walnut cookies': '核桃饼干',
    'Hazelnut cookies': '榛子饼干',
    'Almond cookies': '杏仁饼干',
    'Label printer': '标签打印机',
    'Good manners': '礼貌',
    'Lindworms': '林德蠕虫',
    'Armythril mouse': '阿迈斯里鼠标',
    'Reverse dementia': '反向痴呆症',
    'Humane pesticides': '人道杀虫剂',
    'Mole people': '鼹鼠人',
    'Machine learning': '机器学习',
    'Edible money': '可食用货币',
    'Sick rap prayers': '饶舌祈祷者',
    'Deluxe tailored wands': '豪华定制魔杖',
    'Autopilot': '自动驾驶仪',
    'The advent of chemistry': '化学的出现',
    'The real world': '真实的世界',
    'Second seconds': '第二秒',
    'Quantum comb': '量子梳',
    'Crystal mirrors': '水晶镜子',
    'Bunnypedes': '小松鼠',
    'Kitten assistants to the regional manager': '小猫助理区域经理',
    'Charm quarks': '魅力夸克',
    'Pink biscuits': '粉色饼干',
    'Whole-grain cookies': '全麦饼干',
    'Candy cookies': '糖果饼干',
    'Big chip cookies': '大曲奇饼',
    'One chip cookies': '一个曲奇饼',
    'Sugar baking': '糖烘焙',
    'Sugar craving': '糖分渴求',
    'Sugar aging process': '糖老化过程',
    'Sugar frenzy': '糖的狂热',
    'Sprinkles cookies': '小甜饼',
    'Golden switch': '黄金开关',
    'Classic dairy selection': '选择经典的乳制品',
    'Fanciful dairy selection': '奇特的乳制品选择',
    'Dragon cookie': '龙形饼干',
    'Tin of butter cookies': '奶油饼干罐头',
    'Chimera': '奇美拉',
    'A crumbly egg': '易碎的鸡蛋',
    'How to bake your dragon': '如何烤你的龙',
    'Kitten accountants': '小猫会计',
    'Kitten specialists': '小猫专家',
    'Kitten experts': '小猫能手',
    'Reverse shadows': '反向阴影',
    'The Unbridling': '未被发现的',
    'Wheat triffids': '小麦的由来',
    'Canola oil wells': '菜籽油井',
    '78-hour days': '每天78小时',
    'The stuff rationale': '基本原理',
    'Theocracy': '神权政治',
    'Rabbit trick': '兔子戏法',
    'The final frontier': '最后的边界',
    'Beige goo': '原色古果',
    'Maddening chants': '疯狂的圣歌',
    'Cookietopian moments of maybe': '也许是小饼干的时候',
    'Some other super-tiny fundamental particle? Probably?': '还有其他超微小的基本粒子吗？',
    'Turbo-charged soil': '涡轮增压土壤',
    'Technobsidian mouse': '高科技鼠标',
    'Kitten marketeers': '小猫市场商人',
    'Festivity loops': '节日循环',
    'Persian rice cookies': '波斯米饼干',
    'Pure black chocolate cookies': '纯黑巧克力饼干',
    'Pure white chocolate cookies': '纯白巧克力饼干',
    'Ladyfingers': '松脆饼',
    'Tuiles': '瓦片',
    'Chocolate-stuffed biscuits': '巧克力饼干',
    'Checker cookies': '切克饼干',
    'Butter cookies': '黄油饼干',
    'Cream cookies': '奶油饼干',
    'Quantum electronics': '量子电子学',
    'Asteroid mining': '小行星采矿',
    'Seismic magic': '地震魔法',
    'Rain prayer': '雨中的祈祷',
    'Future almanacs': '未来年鉴',
    'Temporal overclocking': '颞超频',
    'Contracts from beyond': '来自远方的合同',
    'Printing presses': '印刷机',
    'Paganism': '异教',
    'God particle': '上帝粒子',
    'Arcane knowledge': '奥术知识',
    'Magical botany': '神奇植物学',
    'Fossil fuels': '化石燃料',
    'Shipyards': '船厂',
    'Primordial ores': '原始矿石',
    'Gold fund': '黄金基金',
    'Infernal crops': '地狱作物',
    'Abysmal glimmer': '暗淡的微光',
    'Relativistic parsec-skipping': '相对论性的省略',
    'Primeval glow': '原始辉光',
    'Extra physics funding': '额外的物理资金',
    'Chemical proficiency': '化学能力',
    'Light magic': '光明魔法',
    'Mystical energies': '神秘的能量',
    'Synergies Vol. I': '协同效应 I',
    'Synergies Vol. II': '协同效应 II',
    'Golden switch [off]': '黄金开关[关闭]',
    'Golden switch [on]': '黄金开关[开启]',
    'Milk selector': '牛奶选择器',
    'Automatic': '自动',
    'Blue': '蓝色',
    'Red': '红色',
    'White': '白色',
    'Black': '黑色',
    'Gold': '金色',
    'Grandmas': '老奶奶',
    'Displeased grandmas': '不满的老奶奶',
    'Angered grandmas': '愤怒的老奶奶',
    'Money': '钱钱',
    'No sound': '无声',
    'Chime': '钟',
    'all': '全部',
    'Classic': '经典',
    'Cookie Clicker': '无尽的饼干',
    'Info': '信息',
    'Try the beta!': '尝试Beta版！',
    'When you\'re ready,': '当你准备好了，',
    'You are ascending.': '你正在转生。',
    'Plain milk': '纯牛奶',
    'Chocolate milk': '巧克力牛奶',
    'Raspberry milk': '树莓牛奶',
    'Orange milk': '橙汁牛奶',
    'Caramel milk': '焦糖牛奶',
    'Banana milk': '香蕉牛奶',
    'Lime milk': '石灰牛奶',
    'Blueberry milk': '蓝莓牛奶',
    'Strawberry milk': '草莓牛奶',
    'Vanilla milk': '香草牛奶',
    'Honey milk': '蜂蜜牛奶',
    'Coffee milk': '咖啡牛奶',
    'Tea milk': '加茶牛奶',
    'Coconut milk': '椰子牛奶',
    'Cherry milk': '樱桃牛奶',
    'Spiced milk': '五香牛奶',
    'Maple milk': '枫糖牛奶',
    'Zebra milk': '斑马牛奶',
    'Cosmic milk': '宇宙牛奶',
    'Flaming milk': '火红的牛奶',
    'Sanguine milk': '血红色的牛奶',
    'Midas milk': '迈达斯牛奶',
    'Midnight milk': '午夜牛奶',
    'Green inferno milk': '绿色地狱牛奶',
    'Frostfire milk': '霜火牛奶',
    'Soy milk': '豆奶',
    'Enlarged pantheon': '扩大万神殿',
    'Sun festival': '太阳节',
    'Delicious blessing': '美味的祝福',
    'Sacrifices': '牺牲',
    'Golden idols': '金色偶像',
    'Financial zen': '金融禅宗',
    'Exponential interest rates': '指数利率',
    'Chocolate coins': '巧克力硬币',
    'Acid-proof vaults': '耐酸金库',
    'Scissor-resistant credit cards': '抗剪刀的信用卡',
    'Taller tellers': '更高级的出纳员',
    'Caramel macarons': '焦糖马卡龙',
    'Licorice macarons': '甘草马卡龙',
    'Great Baker in the sky': '天上的面包师',
    'Pointier hats': '尖尖的帽子',
    'Beardlier beards': '胡子胡子',
    'Ancient grimoires': '古魔典',
    'Kitchen curses': '厨房诅咒',
    'School of sorcery': '魔法学校',
    'Dark formulas': '黑暗公式',
    'Banker grandmas': '银行家老奶奶',
    'Priestess grandmas': '祭司老奶奶',
    'Witch grandmas': '女巫老奶奶',
    '': '',
    '': '',
    '': '',
    //升级名称结束
    //成就名称开始
    'Wake and bake': '唤醒和烘烤',
    'Making some dough': '做一些面团',
    'So baked right now': '现在就烤好了',
    'Fledgling bakery': '初出茅庐的面包店',
    'Affluent bakery': '富裕的面包店',
    'World-famous bakery': '世界著名的面包店',
    'Cosmic bakery': '宇宙面包店',
    'Galactic bakery': '银河面包店',
    'Universal bakery': '万能面包店',
    'Timeless bakery': '永恒的面包店',
    'Infinite bakery': '无限的面包店',
    'Immortal bakery': '不朽的面包店',
    "Don\'t stop me now": '别拦着我',
    'You can stop now': '你可以停下来',
    'Cookies all the way down': '一路都是饼干',
    'Overdose': '过量',
    'Casual baking': '随意的烘焙',
    'Hardcore baking': '铁杆烘焙',
    'Steady tasty stream': '稳定的美味的流',
    'Cookie monster': '饼干怪兽',
    'Mass producer': '大规模生产',
    'Cookie vortex': '饼干漩涡',
    'Cookie pulsar': '饼干脉冲星',
    'Cookie quasar': '饼干类星体',
    "Oh hey, you\'re still here": '嘿，你还在这儿',
    "Let\'s never bake again": '别再烤了',
    'Sacrifice': '牺牲',
    'Oblivion': '遗忘',
    'From scratch': '从头开始',
    'Neverclick': '永不点击',
    'Clicktastic': '可以点击',
    'Clickathlon': '全能点击',
    'Clickolympics': '点击奥林匹克',
    'Clickorama': '点击奥腊马',
    'Click': '单击',
    'Double-click': '双击',
    'Mouse wheel': '鼠标滚轮',
    'Of Mice and Men': '鼠标和人',
    'The Digital': '数字',
    'Just wrong': '大错特错',
    "Grandma\'s cookies": '奶奶的饼干',
    'Sloppy kisses': '草率的吻',
    'Retirement home': '养老院',
    'My first farm': '我的第一个农场',
    'Reap what you sow': '收获你所播种',
    'Farm ill': '农场生病了',
    'Production chain': '生产链',
    'Industrial revolution': '工业革命',
    'Global warming': '全球变暖',
    'You know the drill': '你知道那个钻',
    'Excavation site': '挖掘现场',
    'Hollow the planet': '挖空地球',
    'Expedition': '探险',
    'Galactic highway': '银河高速公路',
    'Far far away': '遥远的远方',
    'Transmutation': '转化',
    'Transmogrification': '变形',
    'Gold member': '黄金会员',
    'A whole new world': '一个全新的世界',
    "Now you\'re thinking": '现在你在思考了',
    'Dimensional shift': '空间移位',
    'Time warp': '时间扭曲',
    'Alternate timeline': '交替时间线',
    'Rewriting history': '改写历史',
    'One with everything': '其中的一切',
    'Mathematician': '数学家',
    'Base 10': '基数10',
    'Golden cookie': '金色饼干',
    'Lucky cookie': '幸运饼干',
    'A stroke of luck': '好运气',
    'Cheated cookies taste awful': '被骗的饼干味道很糟糕',
    'Uncanny clicker': '诡秘的点击器',
    'Builder': '建设者',
    'Architect': '建筑师',
    'Enhancer': '增强剂',
    'Augmenter': '增益剂',
    'Cookie-dunker': '饼干灌篮高手',
    'Fortune': '幸运',
    'True Neverclick': '真正的永不点击',
    'Elder nap': '老年小睡',
    'Elder slumber': '老年沉睡',
    'Elder': '老年人',
    'Elder calm': '平静的老人',
    'Engineer': '工程师',
    'Leprechaun': '妖精',
    "Black cat\'s paw": '黑猫的爪子',
    'Nihilism': '虚无主义',
    'Antibatter': '防糊剂',
    'Quirky quarks': '古怪夸克',
    'It does matter!': '这很重要',
    'Upgrader': '升级程序',
    'Centennial': '一百周年纪念',
    'Hardcore': '核心',
    'Speed baking I': '快速烘焙 I',
    'Speed baking II': '快速烘焙 II',
    'Speed baking III': '快速烘焙 III',
    'Getting even with the oven': '即使有烤箱',
    'Now this is pod-smashing': '这真是太棒了',
    'Chirped out': '发出叫声',
    'Follow the white rabbit': '跟着白兔',
    'Clickasmic': '点击狂魔',
    'Friend of the ancients': '老人的朋友',
    'Ruler of the ancients': '老人的统治者',
    'Wholesome': '健康',
    'Just plain lucky': '非常幸运',
    'You get nothing': '你什么都没有得到',
    '[X] extra fingers': '[X] 额外的手指',
    'Kitten consultants': '小猫顾问',
    'Self-contained': '自包含',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //成就名称结束
    //天赋名称开始
    'Legacy': '遗物',
    'Basic wallpaper assortment': '基本壁纸分类',
    'Elder spice': '老香料',
    'Residual luck': '残余运气',
    'Fantasteel mouse': '范塔钢鼠标',
    'Nevercrack mouse': '永不崩溃的鼠标',
    'Five-finger discount': '五指折扣',
    'Box of brand biscuits': '品牌饼干盒',
    'Box of macarons': '马卡龙盒子',
    'Tin of british tea biscuits': '一罐英国茶饼干',
    'Starspawn': '星卵',
    'Starsnow': '星雪',
    'Starterror': '星际恐怖',
    'Starlove': '星际之恋',
    'Startrade': '星际贸易',
    'Angels': '天使',
    'Archangels': '大天使',
    'Virtues': '美德',
    'Dominions': '领地',
    'Cherubim': '智天使',
    'Seraphim': '六翼天使',
    'God': '上帝',
    'Twin Gates of Transcendence': '双重超越之门',
    'Heavenly luck': '天上的运气',
    'Lasting fortune': '永恒的财富',
    'Decisive fate': '决定性的命运',
    'Divine discount': '神圣折扣',
    'Divine sales': '神圣销售',
    'Divine bakeries': '神圣的面包店',
    'Starter kit': '启动装置',
    'Starter kitchen': '启动厨房',
    'Halo gloves': '光环手套',
    'Kitten angels': '小猫天使',
    'Unholy bait': '邪恶的诱饵',
    'Sacrilegious corruption': '亵渎神明',
    'Xtreme walkers': '播放器步行者',
    'Permanent upgrade slot I': '永久升级槽 I',
    'Permanent upgrade slot II': '永久升级槽 II',
    'Permanent upgrade slot III': '永久升级槽 III',
    'Permanent upgrade slot IV': '永久升级槽 IV',
    'Permanent upgrade slot V': '永久升级槽 V',
    'Permanent upgrade slot VI': '永久升级槽 VI',
    'Heavenly cookies': '天堂饼干',
    'Wrinkly cookies': '皱纹饼干',
    'Distilled essence of redoubled luck': '翻倍运气的精华',
    'Occult obstruction': '神秘障碍',
    'Glucose-charged air': '葡萄糖空气',
    'Lavender chocolate butter biscuit': '薰衣草巧克力奶油饼干',
    'Lombardia cookies': '伦巴第饼干',
    'Bastenaken cookies': '巴斯顿坎饼干',
    'Pecan sandies': '山核桃饼干',
    'Moravian spice cookies': '摩拉维亚香料饼干',
    'Anzac biscuits': '澳扎克饼干',
    'Buttercakes': '黄油蛋糕',
    'Ice cream sandwiches': '冰淇淋三明治',
    'Stevia Caelestis': '甜菊糖',
    'Diabetica Daemonicus': '糖尿病患者',
    'Sucralosia Inutilis': '舒张症',
    'Lucky digit': '幸运数字',
    'Lucky number': '幸运数',
    'Lucky payout': '幸运的支付',
    'Background selector': '背景选择器',
    'Lucky grandmas': '幸运老奶奶',
    'Keepsakes': '纪念品',
    'Golden cookie alert sound': '金色饼干警报声',
    'Inspired checklist': '灵感清单',
    'Purrchased': '购买',
    'Abaddon': '阿巴登',
    'Heralds': '使者',
    'Belphegor': '贝尔菲格',
    'Mammon': '财神',
    'Satan': '撒旦',
    'Asmodeus': '魔王',
    'Beelzebub': '恶魔',
    'Lucifer': '路西法',
    'Golden cookie sound selector': '金色饼干声音选择器',
    'RandomGen': '随机生成器',
    'per second ': '每秒 ',
    'Muted': '已静音',
    'Mute': '静音',
    'New update!': '有更新！',
    'Options': '选项',
    'or use arrow keys!': '或使用箭头键！',
    'Tasty Sprocket': '美味的链轮',
    'Other versions': '其它版本',
    '1 trillion more cookies': '1 trillion 饼干',
    'Ascend': '转生',
    'Do you REALLY want to ascend?': '您真的要转生吗？',
    'No': '不',
    'Shiny Mitten': '闪亮的手套',
    'Yes!': '是的!',
    'You will keep your achievements.': '你会保留你的成就。',
    'Liquid Puppy': '液体小狗',
    'Lots of other games in there!': '还有很多其他游戏！',
    'Greedy Sprocket': '贪婪链轮',
    'Space Burger': '太空汉堡',
    'The mouse and cursors are': '鼠标和光标是',
    'to bulk-buy or sell': '批量购买或出售',
    'of total CpS': '总计每秒点击数',
    'of a building at a time, or': '一个建筑在同一时刻，或者',
    'Moist cookies.': '潮湿的饼干。',
    'Indentured servitude.': '奴役契约。',
    'Grandmas are': '老奶奶们',
    'grandma': '老奶奶',
    'cookies per second': '每秒获得的饼干',
    'cookie per second': '每秒获得的饼干',
    'cookies baked so far': '到目前为止烘焙的饼干',
    'cookies clicked so far': '到目前为止点击的饼干',
    'Autoclicks once every 10 seconds.': '每10秒自动点击一次。',
    'A nice grandma to bake more cookies.': '一个能烤更多饼干的好奶奶。',
    '[owned ': '[拥有 ',
    '[Upgrade]': '[升级]',
    'Pirate Turtle': '海盗龟',
    'cookie per second (': '饼干每秒 (',
    'cookies per second (': '饼干每秒 (',
    'Grows cookie plants from cookie seeds.': '用饼干种子种植饼干植物。',
    'Bought the farm': '买下农场',
    'each cursor produces': '每个游标产生',
    'each grandma produces': '每个老奶奶产生',
    'twice': '双倍',
    'Robot Pirate': '机器人海盗',
    'cookies harvested so far': '目前收获的饼干',
    'each farm produces': '每个农场生产',
    'Farms are': '农场像',
    '[Achievement]': '[成就]',
    '[Locked]': '[未解锁]',
    '[Unlocked]': '[已解锁]',
    'Frenetic Kitten': '疯狂小猫',
    'General': '常规',
    'Milk': '牛奶',
    'Milk flavors unlocked': '牛奶风味解锁',
    'multiplier ': '倍数',
    'Rank I - Plain milk': '一级-纯牛奶',
    'Raw cookies per second': '原始每秒生产饼干数',
    'Run started': '开始运行',
    'Running version': '运行版本',
    'Statistics': '统计',
    'Upgrades': '升级',
    'Upgrades unlocked': '已解锁升级',
    'Royal Sloth': '皇家树懒',
    'Double Meatball': '双肉丸',
    '[Cookie]': '[饼干]',
    'Volume': '音量',
    'Wipe save': '硬复位',
    'add Mute buttons on buildings': '在建筑物上添加静音按钮',
    'ON': '开启',
    'OFF': '关闭',
    'Back': '返回',
    'Check mod data': '检查mod数据',
    'cookies falling down, etc; disabling may improve performance': '饼干掉下来等； 禁用可能会提高性能',
    'Crumbly Pizza': '脆皮披萨',
    'Export save': '导出存档',
    'cutting-edge visual improvements; disabling may improve performance': '先进的视觉效果； 禁用可能会提高性能',
    'Delete all your progress, including your achievements': '删除所有进度，包括成就',
    'display boxes around upgrades and achievements in stats': '显示有关统计数据的升级和成就的框',
    'how your cookie sounds when you click on it': '当您单击它时，饼干的声音如何',
    'Import save': '导入存档',
    'Load from file': '通过文件加载',
    'Mod data': 'Mod数据',
    'visual improvements; disabling may improve performance': '视觉上的改进； 禁用可能会提高性能',
    'Ninja Turtle': '忍者神龟',
    'You can use this to backup your save or to transfer it to another computer (shortcut for import : ctrl+O': '您可以使用它来备份您的保存或将其转移到另一台计算机（导入的快捷方式：ctrl + O',
    'your cookie will react when you click it': '您的饼干会在您点击时做出反应',
    'your cookies are displayed using a monospace font': '您的饼干使用等宽字体显示',
    'Produces large quantities of cookies.': '产生大量的饼干。',
    'Tasty, if a little unimaginative.': '好吃，如果有点不可思议。',
    'Big Mystery': '大谜团',
    'Click to purrchase.': '点击购买。',
    'Factories are': '工厂',
    'meow may I help you': '喵，我可以帮你吗',
    'more CpS': '更多的CpS',
    'the more milk you have.': '你有的牛奶越多。',
    'You gain': '你获得了',
    'You\'re going places.': '你要去的地方。',
    'You\'re in deep.': '你在深处。',
    'Triple Gnome': '三重侏儒',
    'per grandma.': '每个老奶奶。',
    'Royal Biscuit': '皇家饼干',
    'as efficient. Farms gain': '是有效的。农场获得',
    '[Heavenly]': '[天堂]',
    '1% CpS': '1% CpS',
    'and': '和',
    'also gives you a permanent': '也会给你一个永久的',
    'Are you ready to return to the mortal world?': '您准备好回到凡人世界吗？',
    'Ascending': '转生',
    'can be spent on a variety of permanent transcendental upgrades.': '可以用于各种永久的超越升级。',
    'Click this once you\'ve bought': '购买后，请点击此按钮',
    'Each prestige level grants you a permanent': '每个声望等级授予您一个永久性的',
    'Each time you ascend, the cookies you made in your past life are turned into': '每一次你转生，你在过去生活中做的饼干就会变成',
    'every time you gain a prestige level.': '每次你获得声望等级。',
    'everything you need!': '你需要的一切!',
    'Magic Spaceship': '魔法飞船',
    'Heavenly chips are used to buy heavenly upgrades.': '天堂筹码用于购买天堂升级。',
    '1 chip': '1 筹码',
    'Big Click': '大点击',
    'chips': '筹码',
    'stock': '股票',
    'spooky scary skeletons': '怪异的恐怖骷髅',
    'Seeds': '种子',
    'Radical Teapot': '锥形茶壶',
    'reindeer cookies.': '驯鹿饼干',
    'Profits': '利润',
    'Max': '最大',
    'Load': '加载',
    'Line style': '线的样式',
    'less than 1 second': '少于一秒',
    'JAM': '果酱',
    'Initializing...': '初始化中...',
    'Hire': '雇佣',
    'Hide': '隐藏',
    'Halloween season': '万圣节季节',
    'halloween cookies.': '万圣节饼干。',
    'golden cookie upgrades.': '金色饼干升级。',
    'for the next 24 hours.': '在接下来的24小时。',
    'Fantastic Baker': '神奇的面包师',
    'EGG': '蛋',
    'econds of your highest raw cookies per second.': '每秒钟你最高的原始饼干。',
    'DOUGH JONES INDEX': '面团琼斯指数',
    'Cost scales with unbuffed CpS and increases with every season switch.': '成本随着CpS的减少而增加，并且随着每个季节的变化而增加。',
    'Cost is equal to 1 hour of production.': '成本等于1个小时的生产时间。',
    'cookies while you were away.': '饼干当你不在的时候',
    ', but prevents golden cookies from spawning.': '，但可以防止产生金色饼干。',
    'Color mode': '颜色模式',
    '. All prices are in': '。 所有价格都在',
    '\'Twas the night before Christmas- or was it?': '“是圣诞节前一天晚上吗？或者是吗？',
    '[Switch]': '[切换]',
    '1 cookie': '1 饼干',
    '1 second': '1 秒',
    '2nd loan': '第2次贷款',
    'All': '全部',
    'View Garden': '查看花园',
    'You earned': '你得到了',
    'Your prestige level is currently': '您的声望等级目前为',
    'Welcome back!': '欢迎回来!',
    'View Stock Market': '查看股票市场',
    'View Pantheon': '查看万神殿',
    'View Grimoire': '查看魔典',
    'value': '值',
    'Urban Puppy': '都市小狗',
    '1st loan': '第1笔贷款',
    'Your lucky cookie': '您的幸运饼干',
    'You\'ve switched seasons': '你切换的季节',
    'You\'ve purchased': '您已购买',
    'You like to bite the legs off first, right? How about tearing off the arms? You sick monster.': '你喜欢先咬断它的腿，对吧?把胳膊扯下来怎么样?你这恶心的怪物。',
    '[free ': '[免费 ',
    '[Tier : Berrylium]': '[层 : 铍]',
    '[Tier : Chalcedhoney]': '[层 : 玉髓]',
    '[Tier : Plain]': '[层 : 朴素]',
    '1 sugar lump': '1 糖块',
    '3rd loan': '第3笔贷款',
    'A princely snack!': '王子的点心！',
    'A red hot cherry biscuit that will nudge the target of your affection in interesting directions.': '炽热的樱桃饼干，它将在有趣的方向上推动您的感情目标。',
    'A strange inversion of chocolate milk. For those who are a little bit too hardcore for white chocolate, but not hardcore enough for dark.': '巧克力牛奶的奇怪倒置。适合那些有点喜欢白巧克力，但又不太喜欢黑巧克力的人。',
    'Able to process a higher amount of transactions. Careful though, as taller tellers tell tall tales.': '能够处理更多的事务。不过要小心，因为高个子的人讲的都是大话。',
    'Activating this will': '激活这将',
    'Actually worth a lot of mony.': '其实值很多钱。',
    'Alchemy labs are': '炼金实验室',
    'and when they catch you,': '当他们抓到你的时候，',
    'All the world will be your enemy': '整个世界都将是你的敌人',
    'and your': '和你的',
    'Antimatter condensers are': '反物质冷凝器',
    'Banks are': '银行',
    'Because, uh... they\'re worth it?': '因为,呃…他们值得吗?',
    'Bingo center/Research facility': '宾果游戏中心/研究设施',
    'Bingo.': '宾果。',
    'Boosts your cookie production by': '通过提高您的饼干产量',
    'Business day has started!': '工作日开始了！',
    'Business day is over.': '工作日结束。',
    'Business Day season': '工作日季节',
    'Business. Serious business. This is absolutely all of your business.': '业务。严重的业务。这完全是你的事。',
    'but first they must catch you.': '但首先他们必须抓住你。',
    'Cashew cookies': '腰果饼干',
    'Chancemakers are': '造势者',
    'chocolate cookies': '巧克力饼干',
    'CHOCOVERDOSE.': '巧克力维多塞。',
    'Christmas season': '圣诞节季节',
    'Christmas season has started!': '圣诞季节开始了！',
    'Christmas season is over.': '圣诞节结束了。',
    'Cleaned and sanitized so well you\'d swear they\'re actual biscuits.': '干净消毒得你都能发誓那是真的饼干了。',
    'Click again to cancel season': '再次点击取消季节',
    'Click to level up for': '点击以升级',
    'Click to open selector.': '单击打开选择器。',
    'Click to toggle.': '点击切换。',
    'Cookie crumbs': '饼干屑',
    'cookie dragon egg': '饼干龙蛋',
    'cookie stand': '饼干架',
    'Cookiecoin': '饼干币',
    'Corporate country': '企业国家',
    'Crumbly Pirate': '易碎的海盗',
    'Current': '当前',
    'DO?!': '做？！',
    'Doctrine': '学说',
    'double the calories': '双倍卡路里',
    'DOUBLE THE CHIPS': '双倍筹码',
    'DOUBLE THE TASTY': '双倍美味',
    'Easter season': '复活节季节',
    'Easter season has started!': '复活节已经开始了!',
    'Easter season is over.': '复活节结束了。',
    'eggs.': '蛋.',
    'Good heavens, what did you': '天哪，你做了什么',
    'Grandma-operated science lab and leisure club.': '老奶奶经营的科学实验室和休闲俱乐部。',
    'Grandmas are 105 years older granting': '老奶奶的年龄比原来大105岁',
    'Halloween has started!': '万圣节开始了！',
    'Halloween is over.': '万圣节结束了。',
    'heart biscuits.': '心脏饼干。',
    'I know what you\'ll say. It\'s just cocoa butter! It\'s not real chocolate!': '我知道你会说什么。 只是可可脂！ 这不是真正的巧克力！',
    'If you removed your space helmet, you could probably smell it!': '如果卸下太空头盔，可能会闻到气味！',
    'If you want to bake a cookie from scratch, you must first build a factory.': '如果要从头开始烘烤饼干，则必须首先建立工厂。',
    'Investor': '投资者',
    'Kitchen': '厨房',
    'Lateral expansions': '横向扩展',
    'Lets you change the sound golden cookies make when they spawn.': '让您更改金色饼干产生时的声音。',
    'Lets you pick what flavor of milk to display.': '让您选择要显示的牛奶口味。',
    'Lets you pick which wallpaper to display.': '让您选择要显示的墙纸。',
    'Level 105 grandmas': '105级奶奶',
    'Level 34 cursors': '34级游标',
    'Like': '喜欢',
    'Look to the cookie.': '查看饼干。',
    'Lure even greedier adventurers to retrieve your cookies. Now that\'s a real idol game!': '甚至诱使贪婪的冒险家取回您的饼干。 现在，这是一个真正的偶像游戏！',
    'May only be used once per ascension.': '每个提升只能使用一次。',
    'Meme': '模因',
    'meow meow meow meow': '喵喵喵喵',
    'my purrpose is to serve you, sir': '我的目的是为您服务，先生',
    'Not to be confused with macarons.': '不要和马卡龙搞混了。',
    'Note : don\'t do that.': '注意:不要那样做。',
    'of the potential of your prestige level.': '你的声望等级的潜力。',
    'Oh please.': '哦,请。',
    'Once broken, turning the veil back on costs 24 hours of unbuffed CpS.': '一旦破裂，重新打开面纱将耗费24小时的不受约束的CpS。',
    'Orteil\'s favorite.': 'Orteil的最爱。',
    'Oven': '烤箱',
    'Palmier than you!': '比您更重要！',
    'Prisms are': '棱镜',
    'Privatized planet': '私有化的星球',
    'Regularly unlocks new upgrades': '定期解锁新的升级',
    'Rolling pin': '擀面杖',
    'Romance never goes out of fashion.': '浪漫永远不会过时。',
    'Secret recipe': '秘方',
    'selector': '选择器',
    'Shimmering veil [off]': '闪光的面纱[关闭]',
    'Senate seat': '参议院席位',
    'Shipments are': '发货',
    'Sometimes you feel like one of these. Sometimes you don\'t.': '有时候你会觉得自己是其中一员。有时你不。',
    'Stock share': '股票份额',
    'Supermarket': '超级市场',
    'Sweet firm bosons.': '甜蜜牢固的玻色子。',
    'Tastefully sour, delightful treats.': '酸味十足，美味可口。',
    'Time remaining': '剩余时间',
    'Tiny Portal': '微小的传送门',
    'Tools': '工具',
    'Triggering another season will cancel this one.': '触发另一个季节将取消这个季节。',
    'Triggers': '触发',
    'triple your CpS': '3倍你的Cps',
    'Turning this on will give you a passive': '启用此功能将使您变得被动',
    'Turns cookies into even more cookies.': '将饼干变成更多的饼干。',
    'Turns gold into cookies!': '把黄金变成饼干！',
    'Unlocks': '解锁',
    'Unlocks the': '解锁',
    'Valentine\'s Day season': '情人节季节',
    'when active.': '活动时。',
    'will wake you with a boo': '会用嘘声叫醒你',
    'Wizard towers are': '精灵塔',
    'this ascension.': '这次转生。',
    'They\'re macadamn delicious!': '它们真是美味！',
    'They\'re like tiny sugary burgers!': '他们就像小小的含糖汉堡！',
    'They\'ll never know what hit \'em': '他们永远不会知道什么打他们',
    'they will kill you...': '他们会杀了你...',
    'Full of precious, ancient chocolate.': '装满了珍贵的古老巧克力。',
    'each wizard tower produces': '每个精灵塔产生',
    'each alchemy lab produces': '每个炼金术实验室产生',
    'each antimatter condenser produces': '每个反物质冷凝器产生',
    'each bank produces': '每个银行产生',
    'each chancemaker produces': '每个机会制造者产生',
    'each fractal engine produces': '每个分形引擎产生',
    'each idleverse produces': '每个闲话产生',
    'each javascript console produces': '每个JavaScript控制台产生',
    'each portal produces': '每个传送门产生',
    'each prism produces': '每个棱镜产生',
    'each shipment produces': '每个装船产生',
    'each temple produces': '每个寺庙产生',
    'each time machine produces': '每个时光机器产生',
    'Idleverse': '闲话',
    'cookies transmuted so far': '到目前为止嬗变的饼干',
    'cookies summoned so far': '到目前为止召唤的饼干',
    'cookies spontaneously generated so far': '到目前为止自发产生的饼干',
    'cookies shipped so far': '到目前为止已运送的饼干',
    'cookies retrieved so far': '到目前为止回收的饼干',
    'cookies recovered so far': '到目前为止恢复的饼干',
    'cookies programmed so far': '到目前为止编程的饼干',
    'cookies made from cookies so far': '到目前为止由饼干制成的饼干',
    'cookies hijacked so far': '到目前为止被劫持的饼干',
    'cookies discovered so far': '到目前为止发现的饼干',
    'cookies converted so far': '到目前为止已转换的饼干',
    'cookies condensed so far': '到目前为止冷凝的饼干',
    'cookies banked so far': '到目前为止存银行的饼干',
    'Converts light itself into cookies.': '将光本身转换为饼干。',
    'Condenses the antimatter in the universe into cookies.': '将宇宙中的反物质浓缩为饼干。',
    'Brings in fresh cookies from the cookie planet.': '带来来自饼干星球的新鲜饼干。',
    'and fall after': '并在之后',
    'Brings cookies from the past, before they were even eaten.': '带来了过去的饼干，它们甚至还没被吃掉。',
    'Generates cookies out of thin air through sheer luck.': '完全靠运气就能凭空生成饼干。',
    'Grandma\'s favorite?': '老奶奶的最爱?',
    'Quite.': '相当。',
    'I mean, you\'re welcome to try.': '我是说，你可以试试。',
    'If it ain\'t dutch, it ain\'t much.': '如果不是荷兰的，那也不算多。',
    'is coalescing here, attracted by your accomplishments.': '聚集在这里，被你的成就所吸引。',
    'Not exactly cookies, but you won\'t care once you\'ve tasted one of these.': '不完全是饼干，但是一旦您尝过其中一种，就不会在意了。',
    'Note that sugar lumps keep growing when the game is closed.': '请注意，游戏关闭时糖块会继续增长。',
    'Once a sugar lump is harvested, another one will start growing in its place.': '一旦收获了一块糖，另一块糖就将开始生长。',
    'Pinwheel cookies': '风车饼干',
    'ripen after': '熟了之后',
    'sugar lump': '糖块',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Javascript consoles are': 'Javascript控制台',
    'It\'s like two chocolate chip cookies! But brought together with the magic of cream! It\'s fiendishly perfect!': '就像两块巧克力碎饼干!还加上了奶油的魔力!这是极其完美!',
    'Creates cookies from the very code this game was written in.': '从编写该游戏的代码创建饼干。',
    'Opens a door to the Cookieverse.': '打开一扇通往饼干世界的门。',
    'Pistachio shells now removed after multiple complaints.': '在多次投诉后，开心果壳被移除。',
    'Summons cookies with magic spells.': '用魔法咒语召唤饼干。',
    'Tastes like a morning stroll through a fragrant forest, minus the clouds of gnats.': '尝起来就像清晨漫步在芬芳的森林里，没有了成群的蚊蚋。',
    'Temples are': '寺庙',
    'Tests have shown increased thaumic receptivity relative to the geometric proportions of wizardly conic implements.': '测试表明，相对于神奇的圆锥形器具的几何比例增加了感受性。',
    'Thank you for adopting this robust, fun-loving cookie dragon! It will bring you years of joy and entertainment.': '感谢您采用这种坚固耐用，喜欢娱乐的饼干龙！ 它将带给您数年的欢乐和娱乐。',
    'thanks to residual luck': '多亏了运气',
    'The effective boost is': '有效的提升是',
    'The veil is very fragile and will break if you click the big cookie or any golden cookies or reindeer.': '面纱非常脆弱，如果您单击大饼干或任何金色饼干或驯鹿，它会破裂。',
    'There used to be a cookie here. Now there isn\'t.': '这里曾经有一个饼干。 现在没有了。',
    'There\'s been countless other idle universes running alongside our own. You\'ve finally found a way to hijack their production and convert whatever they\'ve been making into cookies!': '我们周围还有无数其他闲置的宇宙。 您终于找到了一种劫持他们的产品并将他们所做的一切转换为饼干的方法！',
    'Some experts have pointed to the walnut\'s eerie resemblance to the human brain as a sign of its sentience - a theory most walnuts vehemently object to.': '一些专家指出，核桃与人类大脑有着惊人的相似之处，这是一种感知能力的表现——大多数核桃强烈反对这一理论。',
    'Let me tell you about cashews. Cashews are not nuts, but seeds that grow out of curious red or yellow fruits - which can be eaten on their own, or made into drinks. The shell around the nut itself contains a nasty substance that stains and irritates the hands of whoever handles it for too long. But that\'s okay, since now that you\'ve read this you\'ll make sure it doesn\'t get in the cookies! Oh, you\'ve already eaten how many? Okay then.': '让我告诉您有关腰果的信息。 腰果不是坚果，而是种子，它们是从奇特的红色或黄色水果中长出来的，可以单独食用或制成饮料。 螺母周围的外壳本身含有一种讨厌的物质，该物质会弄脏和刺激长时间使用它的人的手。 但这没关系，因为既然您已经阅读了此书，就可以确保它不会出现在饼干中！ 哦，你已经吃了多少？ 好吧。',
    'Keep in a dry and cool place, and away from other house pets. Subscription to home insurance is strongly advised.': '存放在干燥阴凉的地方，并远离其他室内宠物。 强烈建议订阅家庭保险。',
    'Get yourself some jam cookies!': '给自己弄些果酱饼干！',
    'Get rid of the grime and let more light in.': '清除污垢，让更多的光线进入室内。',
    'From': '从',
    'for 1 hour, at the cost of': '1小时，费用为',
    'Flaky, but not unreliable. Some people go crazy for these.': '有点不靠谱，但并不不靠谱。有些人很喜欢这些。',
    'Evergreens in pastry form. Yule be surprised what you can come up with.': '糕点状的常青树。对你能想出的东西感到惊讶。',
    'Elaborated on the nano-scale, the coating on this biscuit is able to refract light even in a pitch-black environment.': '在纳米尺度上，这种饼干上的涂层即使在漆黑的环境中也能折射光线。',
    'Don\'t forget to visit the heavenly lemonade stand afterwards. When afterlife gives you lemons...': '之后别忘了去天堂般的柠檬水摊看看。当来世给你柠檬……',
    'Nevermind': '没关系',
    'no brokers': '没有经纪人',
    'NUT': '坚果',
    'of Santa\'s gifts.': '圣诞老人的礼物。',
    'Please paste in the code that was given to you on save export.': '请粘贴之前导出的游戏存档代码。',
    'Your': '你的',
    'Yes': '是的',
    'This is the first heavenly upgrade; it unlocks the': '这是天堂的第一次升级； 它解锁',
    'We\'ve all been waiting for you.': '我们都在等你。',
    'The more levels you have, the more cookies they require.': '您拥有的等级越高，所需的饼干就越多。',
    'system.': '系统。',
    'So long, cookies.': '久违了，饼干。',
    'prestige level': '声望等级',
    'Prestige level': '声望等级',
    'prestige': '声望',
    'per level.': '每一级。',
    'McBaker': '麦克贝克',
    'each factory produces': '每个工厂生产',
    'cookies mass-produced so far': '饼干批量生产至今',
    'farm.': ' 农场.',
    'flavors unlocked': '口味已解锁',
    'is gained with each achievement. It can unlock unique upgrades over time.': '每一项成就都会得到回报。 随着时间的推移，它可以解锁独特的升级。',
    'Your cookies sell very well in distant countries.': '您的饼干在遥远的国家/地区非常畅销。',
    'Sweet Chip': '甜薯片',
    'mine.': ' 矿山.',
    'Have': '拥有 ',
    'About': '关于',
    '[Purchased]': '[已购买]',
    'visual display of your cursors': '可视化显示您的光标',
    'view and delete save data created by mods': '查看和删除存档mod创建的数据',
    'Use this to keep backups on your computer': '用这个在你的电脑上做备份',
    'These are the mods present in your save data. You may delete some of this data to make your save file smaller.': '这些是在你的存档数据中出现的mod。您可以删除其中的一些数据，使存档文件变小。',
    'the game will be less resource-intensive when out of focus': '当焦点不集中时，游戏的资源消耗将会减少',
    'the game will ask you to confirm when you close the window': '当你关闭窗口时，游戏会要求你确认',
    'the game will ask you to confirm before spending sugar lumps': '游戏会要求你在消费糖块之前确认',
    'some grandmas will be named after Patreon supporters': '有些奶奶会以Patreon粉丝的名字命名',
    'shorten big numbers': '缩短大数字',
    'Save to file': '保存为文件',
    'Settings': '设置',
    'Save manually (the game autosaves every 60 seconds; shortcut : ctrl+S': '手动保存(游戏每60秒自动保存一次;快捷方式:按ctrl + S',
    'only appears with enough achievements': '只显示达成的成就',
    'on slower computers, the game will put itself in sleep mode when it\'s inactive and starts to lag out; offline CpS production kicks in during sleep mode': '在较慢的计算机上，游戏处于不活动状态并开始落后时，游戏将进入睡眠模式； 睡眠模式下开始离线CpS生产',
    'numbers that pop up when clicking the cookie': '点击饼干时弹出的数字',
    'Save': '保存',
    'notifications disappear much faster': '通知消失得更快',
    'No mod data present.': '当前没有mod数据。',
    'Mines are': '矿山',
    'Look ma, both hands!': '妈妈快看，双手！',
    'Just what you kneaded.': '就是你揉的东西。',
    'It\'s chocolate, I swear.': '这是巧克力，我发誓。',
    'Cute Cookie': '可爱的饼干',
    'Cookie production multiplier': '饼干生产倍数',
    'A pink, volatile gas, found in the depths of some chocolate caves.': '一种粉红色的挥发性气体，存在于一些巧克力洞穴的深处。',
    'Minimize this building': '最小化这座建筑',
    'Mines out cookie dough and chocolate chips.': '挖出饼干面团和巧克力片。',
    'Mines': '矿山',
    'Greedy Meatball': '贪婪的肉丸',
    'Game saved': '游戏已保存',
    'Farms': '农场',
    'each mine produces': '每座矿山生产',
    'display this building': '显示此建筑',
    'cookies mined so far': '到目前为止已开采的饼干',
    'highest this ascension ': '本次转生最高',
    'Hand-made cookies': '手工制作的饼干',
    'Golden cookie clicks': '金色饼干点击次数',
    'Cookies per second': '每秒得到的饼干',
    'Cookies per click': '每次点击得到的饼干',
    'Cookies in bank': '银行中的饼干',
    'Cookies baked (this ascension': '烘焙的饼干(本次转生',
    'Cookies baked (all time': '烘焙的饼干(所有时间',
    'cookie in one ascension.': '一次转生中的饼干。',
    'cookies in one ascension.': '一次转生中的饼干。',
    'Cookie clicks': '饼干点击次数',
    'Buildings owned': '拥有的建筑',
    'Bake': '烘焙',
    'all time ': '全部时间 ',
    'Achievements unlocked': '成就已解锁',
    'Achievements': '成就',
    'Righteous Booty': '正当的战利品',
    'Rake in the dough!': '赚大钱!',
    'Click to purchase.': '点击购买。',
    'You can share tips and questions about Cookie Clicker and all our other games!': '你可以分享关于《无尽的饼干》和我们所有其他游戏的技巧和问题!',
    'There\'s neat rewards for patrons too!': '顾客也会得到丰厚的回报！',
    'Support us on Patreon and help us keep updating Cookie Clicker!': '在Patreon上支持我们，帮助我们不断更新《无尽的饼干》!',
    'Play Cookie Clicker on your phone!': '在你的手机上玩《无尽的饼干》 !',
    'Our official discord server.': '我们的官方discord服务器。',
    'Orteil\'s twitter, which frequently features game updates.': 'Orteil的twitter，经常发布游戏更新。',
    'Orteil\'s tumblr, which frequently features game updates.': 'Orteil的tumblr，经常发布游戏更新。',
    'Heralds couldn\'t be loaded. There may be an issue with our servers, or you are playing the game locally.': '使者无法加载。可能是我们的服务器有问题，或者你在本地玩游戏。',
    'Heralds benefit everyone playing the game, regardless of whether you donated.': '不管您是否捐赠，使者都会使每个玩游戏的人受益。',
    'Each herald gives everyone +1% CpS.': '每个使者给每个人+ 1％CPS。',
    'Cookie Clicker shirts, hoodies and stickers!': '《无尽的饼干》周边衬衫，帽衫和贴纸！',
    'Back to our homepage!': '回到我们的主页！',
    'Back to Orteil\'s subdomain!': '回到Orteil的子网站！',
    'are people who have donated to our highest Patreon tier, and are limited to 100.': '向我们最高的Patreon阶层捐款的人，数量上限为100人。',
    'Android only; iOS version will be released later': '仅限Android； iOS版本将在以后发布',
    'A thing we made that lets you write random generators.': '我们做的东西，使您可以编写随机生成器。',
    'A thing we made that lets you create your own idle games using a simple scripting language.': '我们做的东西，使您可以使用简单的脚本语言来创建自己的放置游戏。',
    'You will lose your progress and start over from scratch.': '您将失去当前的游戏进度，并从头开始。',
    'All your cookies will be converted into prestige and heavenly chips.': '您所有的饼干都将被转换成声望和天堂筹码。',
    'You can also press': '你也可以按',
    'Water Burglar': '水贼',
    'it... it hurts to click...': '它...它被点击会很痛...',
    'as efficient.': '那样高效。',
    'Achievement unlocked': '成就解锁',
    '^ Sponsored link ^': '^赞助链接^',
    'Triple Click': '三点击',
    'This is taking longer than expected.': '这比预期的时间要长。',
    'Buildings': '建筑',
    'To do so, go to Options and hit "Export save" or "Save to file"!': '要做到这一点，请进入选项并点击“导出存档”或“保存到文件”!',
    'Your browser may not be recent enough to run Cookie Clicker.': '您的浏览器可能不够新，无法运行本游戏。',
    'You\'ve been on this run for': '你本轮游戏持续了 ',
    'You need': '你需要',
    'You might want to update, or switch to a more modern browser such as Chrome or Firefox.': '你可能想要更新，或者切换到更现代的浏览器，如Chrome或Firefox。',
    'Von Cupcake': '冯杯形蛋糕',
    'Stats': '统计',
    'Slow connection? If not, please make sure your javascript is enabled, then refresh.': '连接缓慢？ 如果没有，请确保您的JavaScript已启用，然后刷新。',
    'Antim. condenser': '安蒂姆。 冷凝器',
    'Ascending now would grant you no prestige.': '现在转生不会给你任何声望。',
    'Back up your save!': '备份您的存档!',
    '"Buildings': '建筑',
    'Buy': '购买',
    'Drag the screen around': '拖动屏幕周围',
    'for the next level.': '下一个级别。',
    'If problems persist, this might be on our side - wait a few minutes, then hit ctrl+f5!': '如果问题仍然存在，则这可能是我们这边的问题-等待几分钟，然后按ctrl + f5！',
    'Javascript console': 'Javascript控制台',
    'Live version': '最新版本',
    'Loading...': '加载中...',
    'lvl': '等级',
    'Menu': '菜单',
    'Merch!': '周边！',
    'Ninja Pirate': '忍者海盗',
    'Reincarnate': '转生',
    'Sell': '出售',
    'Store': '商店',
    'click Reincarnate.': '点击“转生”。',
    'Consider unblocking our site or checking out our': '考虑解除屏蔽或访问我们的网站',
    'Cookie Clicker for Android': '安卓版',
    'Cookie Clicker is mainly supported by ads.': '本游戏主要由广告支持。',
    'Don\'t show this again': '不再显示',
    'Game loaded': '游戏已加载',
    'Idle Game Maker': '放置游戏制作器',
    'Hello again! Just a reminder that you may want to back up your Cookie Clicker save every once in a while, just in case.': '再一次问好！ 提醒您，您可能需要备份游戏存档，以防万一。',
    //天赋名称结束
    //新闻
    'Your family accepts to try some of your cookies.': '你的家人愿意尝尝你的饼干。',
    'Your first batch goes to the trash. The neighborhood raccoon barely touches it.': '你的第一批饼干被扔进垃圾桶。附近的浣熊几乎没碰过它。',
    'You feel like making cookies. But nobody wants to eat your cookies.': '你想做饼干。但没人想吃你的饼干。',
    'Your cookies are popular in the neighborhood.': '你的饼干在附近很受欢迎。',
    'Why don\'t you visit more often?': '您为什么不常去呢？',
    'We\'re nice grandmas.': '我们是好奶奶。',
    'RE:RE:thought you\'d get a kick out of this ;)': '复读：复读：认为您会对此有所帮助；）',
    'prod prod': '戳戳',
    'People are starting to talk about your cookies.': '人们开始谈论你的饼干了。',
    'Come give grandma a kiss.': '来，给老奶奶一个吻。',
    'Call me...': '打给我...',
    'Your cookies are talked about for miles around.': '你的曲奇饼方圆几英里都在谈论。',
    'Your cookies now have their own website!': '你的饼干现在有自己的网站!',
    'Your cookies bring all the boys to the yard.': '你的饼干把所有男孩都吸引来了。',
    'News : cookie farms release harmful chocolate in our rivers, says scientist!': '新闻:科学家称，饼干农场向河流中释放有害巧克力!',
    'News : free-range farm cookies popular with today\'s hip youth, says specialist.': '新闻:专家说，自由放养的农场曲奇在当今时髦的年轻人中很流行。',
    'News : "at this point, cookies permeate the economy", says economist. "If we start eating anything else, we\'re all dead."': '新闻：经济学家说：“在这一点上，饼干渗透到整个经济中”。 “如果我们开始吃其他东西，我们都死定了。”',
    'News : don\'t miss tonight\'s interview of Von Cupcake by Bloprah!': '新闻：千万不要错过今晚Bloprah对Von Cupcake的采访！',
    'News : don\'t miss tonight\'s interview of Von Cupcake by Von Cupcake\'s own evil clone!': '新闻：不要错过今晚对冯·科帕奇（Von Cupcake）自己的邪恶克隆人对冯·帕奇（Von Cupcake）的采访！',
    'News : farm cookies deemed unfit for vegans, says nutritionist.': '新闻：营养学家说，农场饼干被认为不适合素食主义者。',
    'News : flavor text kind of unsavory, study finds.': '新闻：研究发现味道文字有点不好。',
    'News : flavor text not particularly flavorful, study finds.': '新闻：研究发现，风味文字不是特别美味。',
    'News : foreign politician involved in cookie-smuggling scandal.': '新闻：涉嫌走私饼干丑闻的外国政客。',
    'News : fossil records show cookie-based organisms prevalent during Cambrian explosion, scientists say.': '新闻：科学家说，化石记录显示在寒武纪爆炸期间普遍存在基于曲奇的生物。',
    'News : genetically-modified chocolate controversy strikes cookie farmers!': '新闻：转基因巧克力的争议袭击了饼干种植者！',
    'News : hundreds of tons of cookies dumped into starving country from airplanes; thousands dead, nation grateful.': '新闻：数百吨饼干从飞机上倒入饥饿的国家；成千上万的人死亡，国家感激不尽。',
    'News : irate radio host rambles about pixelated icons. "None of the cookies are aligned! Can\'t anyone else see it? I feel like I\'m taking crazy pills!"': '新闻：愤怒的电台主持人大肆宣传像素化图标。 “没有一个饼干是对齐的！其他人看不到吗？我觉得我正在服用疯狂的药丸！”',
    'News : is our media controlled by the cookie industry? This could very well be the case, says crackpot conspiracy theorist.': '新闻：我们的媒体是否受Cookie行业控制？骗子阴谋论者说，情况很可能是这样。',
    'News : major city being renamed Von Cupcakeville after world-famous cookie manufacturer.': '新闻：大城市因举世闻名的饼干制造商而更名为Von Cupcakeville。',
    'News : man dies in cookie-eating contest; "a less-than-impressive performance", says judge.': '新闻：男子死于吃饼干比赛；法官说：“表现不及令人印象深刻”。',
    'News : man found allergic to cookies; "what a weirdo", says family.': '新闻：男子发现对饼干过敏；家人说：“什么怪胎”。',
    'News : minor cookie-related incident turns whole town to ashes; neighboring cities asked to chip in for reconstruction.': '新闻：与Cookie相关的小事件使整个城市化为灰烬；邻近城市要求介入重建。',
    'News : movie cancelled from lack of actors; "everybody\'s at home eating cookies", laments director.': '新闻：电影因缺少演员而取消； “每个人都在家吃饼干”，感叹导演。',
    'News : mysterious illegal cookies seized; "tastes terrible", says police.': '新闻：查获了神秘的非法饼干；警察说，“味道很糟”。',
    'News : nation cheers as legislators finally outlaw lack of cheerfulness!': '新闻：国家欢呼，因为立法者最终宣布缺乏欢乐！',
    'News : nation cheers as legislators finally outlaw playing other games than Cookie Clicker!': '新闻：全国人民欢呼，因为立法者最终宣布禁止使用Cookie Clicker以外的其他游戏！',
    'News : nation cheers as legislators finally outlaw the internet!': '新闻：当立法者最终宣布互联网非法时，国家为之欢呼！',
    'News : new cookie-based religion sweeps the nation.': '新闻：基于cookie的新宗教席卷全国。',
    'News : new popularity survey says Von Cupcake\'s the word when it comes to cookies.': '新闻：一项新的人气调查显示，当谈到Cookie时，Von Cupcake就是这个词。',
    'News : new species of giant squids discovered in distant country; "yup, tastes like cookies", says biologist.': '新闻：在遥远的国家发现了新的巨型鱿鱼物种； “是的，味道像饼干”，生物学家说。',
    'News : new species of horses discovered in distant country; "yup, tastes like cookies", says biologist.': '新闻：在遥远的国家发现了新的马种； “是的，味道像饼干”，生物学家说。',
    'News : new species of nurse sharks discovered in distant country; "yup, tastes like cookies", says biologist.': '新闻：在遥远的国家发现了新的哺乳类鲨鱼； “是的，味道像饼干”，生物学家说。',
    'News : new species of sea squirts discovered in distant country; "yup, tastes like cookies", says biologist.': '新闻：在遥远的国家发现了新种类的海鞘； “是的，味道像饼干”，生物学家说。',
    'News : obesity epidemic strikes nation; experts blame that darn rap music.': '新闻：肥胖病流行袭击国家；专家责怪该死的说唱音乐。',
    'News : overgrown cookies found in fishing nets, raise questions about hormone baking.': '新闻：在渔网中发现长满饼干的饼干引发了有关激素烘烤的问题。',
    'News : people all over the internet still scratching their heads over nonsensical reference : "Okay, but why an egg?"': '新闻：互联网上的人们仍然为毫无意义的参考而scratch之以鼻：“好吧，那为什么要鸡蛋呢？”',
    'News : person typing these wouldn\'t mind someone else breaking the news to THEM, for a change.': '新闻：输入这些信息的人不会介意其他人将新闻发布给THEM，以进行更改。',
    'News : pet goblins, dangerous fad or juicy new market?': '新闻：宠物妖精，危险的时尚还是多汁的新市场？',
    'News : pet velvet worms, dangerous fad or juicy new market?': '新闻：宠物天鹅绒蠕虫，危险时尚还是多汁的新市场？',
    'News : pun in headline infuriates town, causes riot. 21 wounded, 5 dead; mayor still missing.': '新闻：双关语激怒了城镇，引发了骚乱。 21人受伤，5人死亡；市长仍然失踪。',
    'News : scientist predicts imminent cookie-related "end of the world"; becomes joke among peers.': '新闻：科学家预计即将出现与Cookie相关的“世界末日”；在同龄人之间开玩笑。',
    'News : scientists establish that the deal with airline food is, in fact, a critical lack of cookies.': '新闻：科学家们发现，与航空食品的交易实际上是严重缺乏饼干的。',
    'News : trace amounts of cookie particles detected in most living creatures, some of which adapting them as part of new and exotic metabolic processes.': '新闻：在大多数生物中都检测到痕量的曲奇颗粒，其中一些适应了新的和新奇的新陈代谢过程。',
    'News : viral video "Too Many Cookies" could be "a grim commentary on the impending crisis our world is about to face", says famous economist.': '新闻：著名经济学家说，病毒视频“饼干太多”可能是“对我们世界即将面临的危机的严峻评论”。',
    'News : Von Cupcake-brand cookies "decidedly cookier than competitors", says consumer survey.': '新闻：消费者调查显示，Von Cupcake品牌的曲奇“肯定比竞争对手的曲奇”。',
    'News : Von Cupcake-brand cookies "more fashionable than competitors", says consumer survey.': '新闻：消费者调查显示，Von Cupcake品牌的曲奇“比竞争对手更时尚”。',
    'News : what do golden cookies taste like? Study reveals a flavor "somewhere between spearmint and liquorice".': '新闻：金曲奇的味道如何？研究表明“在留兰香和甘草之间的某种风味”。',
    'News : what do wrath cookies taste like? Study reveals a flavor "somewhere between blood sausage and seawater".': '新闻：愤怒饼干的味道如何？研究显示“在血肠和海水之间的某个地方”的味道。',
    'News : what makes cookies taste so right? "Probably all the [*****] they put in them", says anonymous tipper.': '新闻：是什么使饼干的味道如此正确？ “可能是他们放进去的所有[*****]”，匿名小费说。',
    'Nws : ky btwn W and R brokn, plas snd nw typwritr ASAP.': '新闻：ky btwn W和R brokn，请尽快提供打字机。',
    'News : "accusations of cookie abuse are only vile slander", reveals celebrity.': '新闻：名人透露：“滥用Cookie的指控仅是诽谤”。',
    'News : "all-you-can-eat" cookie restaurant opens in big city; waiters trampled in minutes.': '新闻：“无限量供应”饼干餐厅在大城市开业；服务员在几分钟内被践踏。',
    'News : "alright, I\'ll say it - I\'ve never eaten a single cookie in my life", reveals celebrity.': '新闻：名人说：“好吧，我会说它-我一生中从未吃过一块饼干。”',
    'News : "average person bakes 1 cookie a year" factoid actually just statistical error; Von Cupcake, who has produced 45,750 cookies in their lifetime, is an outlier and should not have been counted.': '新闻：“普通人每年烘烤1个cookie”的事实实际上只是统计错误；冯·杯形蛋糕（Von Cupcake）一生中生产过45,750个饼干，这是一个离群值，因此不应该算在内。',
    'News : "cookies are the secret behind my perfect skin", reveals celebrity.': '新闻：“饼干是我完美肌肤的秘密”，这表明名人。',
    'News : "cookies helped me stay sane while filming my upcoming movie", reveals celebrity.': '新闻：名人透露：“ cookies帮助我在拍摄即将上映的电影时保持理智”。',
    'News : "cookies really helped me when I was feeling low", reveals celebrity.': '新闻：名人透露：“当我情绪低落时，饼干确实对我有帮助”。',
    'News : "do your cookies contain nurse sharks?", asks PSA warning against counterfeit cookies.': '新闻：“您的cookie中是否含有鲨鱼鲨鱼？”，要求PSA警告不要使用伪造的cookie。',
    'News : "do your cookies contain puffins?", asks PSA warning against counterfeit cookies.': '新闻：“您的cookie包含海雀吗？”，要求PSA警告不要使用伪造的cookie。',
    'News : "I just can\'t stop eating cookies. I think I seriously need help", reveals celebrity.': '新闻：名人透露：“我无法停止吃饼干。我认为我急需帮助”。',
    'News : "I\'ll say one word, just one : cookies", reveals celebrity.': '新闻：“我只说一个字，一个就说：饼干”，这表明了名人。',
    'News : "I\'m all about cookies", reveals celebrity.': '新闻：名人透露：“我只想吃饼干”。',
    'News : "I\'m not addicted to cookies. That\'s just speculation by fans with too much free time", reveals celebrity.': '新闻：名人透露：“我对Cookie并不上瘾。这只是闲暇时间过多的粉丝的猜测。”',
    'News : "I\'ve had dreams about cookies 3 nights in a row now. I\'m a bit worried honestly", reveals celebrity.': '新闻：名人透露：“我已经连续三晚梦见饼干了。老实说，我有点担心。”',
    'News : "memes from last year somehow still relevant", deplore experts.': '新闻：专家们对“去年的模因仍然有意义”表示遗憾。',
    'News : "Ook", says interviewed orangutan.': '新闻：接受采访的猩猩说，“好的”。',
    'News : "the universe pretty much loops on itself," suggests researcher; "it\'s cookies all the way down."': '新闻：研究人员说：“宇宙几乎在自发地循环。” “一直都是饼干。”',
    'News : "Von Cupcake" set to be this year\'s most popular baby name.': '新闻：“ Von纸杯蛋糕”将成为今年最受欢迎的婴儿名字。',
    'News : all-cookie restaurant opening downtown. Dishes such as braised cookies, cookie thermidor, and for dessert : crepes.': '新闻：全曲奇餐厅在市中心开业。菜式，例如炖曲奇，曲奇饼干和甜品：可丽饼。',
    'News : area woman goes on journey of introspection, finds cookies : "I honestly don\'t know what I was expecting."': '新闻：该地区的妇女正在进行内省，发现了饼干：“老实说，我不知道我在期待什么。”',
    'News : comedian forced to cancel cookie routine due to unrelated indigestion.': '新闻：由于不相关的消化不良，喜剧演员被迫取消Cookie程序。',
    'News : cookie emoji most popular among teenagers, far ahead of "judgemental OK hand sign" and "shifty-looking dark moon", says study.': '新闻：研究表明，cookie表情符号在青少年中最为流行，远远超过了“判断性的OK手势”和“动感的暗月”。',
    'News : cookie farms suspected of employing undeclared elderly workforce!': '新闻：饼干农场涉嫌雇用未申报的老年人劳动力！',
    'News : cookie shortage strikes town, people forced to eat cupcakes; "just not the same", concedes mayor.': '新闻：饼干短缺袭击了小镇，人们被迫吃纸杯蛋糕；市长承认：“只是不一样”。',
    'News : cookie-flavored cereals break all known cereal-related records': '新闻：曲奇味谷物打破了所有已知的谷物相关记录',
    'News : cookies could be the key to eternal life, say scientists.': '新闻：科学家说，饼干可能是永生的关键。',
    'News : cookies found to make blowfish less hungry!': '新闻：发现饼干可以减少河豚的饥饿感！',
    'News : cookies go well with sauteed velvet worms, says controversial chef.': '新闻：有争议的厨师说，饼干与炒天鹅绒蠕虫很搭配。',
    'News : cookies now illegal in some backwards country nobody cares about. Political tensions rising; war soon, hopefully.': '新闻：在一些落后的国家，cookies现在是非法的，没人在乎。政治紧张局势加剧；希望不久战争爆发。',
    'News : cookies now more popular than lamps, says study.': '新闻：研究表明，饼干比灯现在更受欢迎。',
    'News : cookies now more popular than whatever it is we ate before, says study.': '新闻：研究表明，现在的cookie比以前吃过的任何东西都更受欢迎。',
    'News : cookies tested on mole rats, found to have no ill effects.': '新闻：在mole鼠身上测试的曲奇，没有任何不良影响。',
    'News : doctors advise against new cookie-free fad diet.': '新闻：医生建议不要使用新的无饼干时尚饮食。',
    'News : doctors recommend twice-daily consumption of fresh cookies.': '新闻：医生建议每天食用两次新鲜饼干。',
    'News : "cookies helped me stay thin and healthy", reveals celebrity.': '新闻：名人透露：“饼干帮助我保持了瘦弱和健康”。',
    'News : man robs bank, buys cookies.': '新闻：男子抢劫银行，购买饼干。',
    'News : obesity epidemic strikes nation; experts blame aliens.': '新闻：肥胖病流行袭击国家； 专家责怪外星人。',
    'We all gotta start somewhere.': '我们都必须从某个地方开始。',
    'Your cookies are worth a lot of money.': '你的饼干价值很多钱。',
    'News : "do your cookies contain mole rats?", asks PSA warning against counterfeit cookies.': '新闻:“你的饼干里有鼹鼠吗?”PSA警告假冒饼干。',
    'News : births of suspiciously bald babies on the rise; ancient alien cabal denies involvement.': '新闻:出生的可疑秃头婴儿数量在上升;古代外星人阴谋否认参与。',
    'News : cookie-flavored popcorn pretty damn popular; "we kinda expected that", say scientists.': '新闻:饼干味的爆米花非常受欢迎;科学家们说:“我们有点预料到这一点。”',
    'News : is our planet getting lighter? Experts examine the effects of intensive chocolate mining.': '新闻:我们的星球越来越轻了吗?专家们研究了巧克力密集开采的影响。',
    'News : chocolate mines found to cause earthquakes and sinkholes!': '新闻：巧克力地雷被发现造成地震和塌陷！',
    'News : cookies found to make goblins more handsome!': '新闻：发现饼干可以使哥布林变得更帅！',
    'No raisin to hate these.': '没有葡萄干讨厌这些。',
    'News : man wakes up from coma, babbles incoherently about some supposed "non-cookie food" we used to eat.': '新闻:一名男子从昏迷中醒来，语无伦次地说着一些我们以前吃的所谓的“非饼干食品”。',
    'People come from very far away to get a taste of your cookies.': '人们从很远的地方来品尝你的饼干。',
    'News : pet crayfish, dangerous fad or juicy new market?': '新闻:宠物小龙虾，危险的时尚还是多汁的新市场?',
    'News : don\'t miss tonight\'s interview of Von Cupcake by Blimmy Blimmel!': '新闻:不要错过今晚布里米·布里梅尔对冯·纸杯蛋糕的采访!',
    'Neeeeews : "neeeew EEEEEE keeeeey working fineeeeeeeee", reeeports gleeeeeeeeful journalist.': '新新新闻 : "新新新 EEEEEE 键键键键 工作得很好好好好好好", 愉快快快快快报报报报道的记者.',
    'News : cookieverse portals suspected to cause fast aging and obsession with baking, says study.': '新闻：研究表明，cookieverse门户网站被怀疑会导致快速老化和对烘焙的痴迷。',
    'News : "Any sufficiently crude magic is indistinguishable from technology", claims renowned technowizard.': '新闻：著名的技术专家声称：“任何足够原始的魔法都无法与技术区分开。”',
    'News : "do not settle near portals," says specialist; "your children will become strange and corrupted inside."': '新闻：“不要在门户附近定居，”专家说。 “您的孩子在里面会变得陌生和腐败。”',
    'News : "explain to me again why we need particle accelerators to bake cookies?" asks misguided local woman.': '新闻：“再次向我解释为什么我们需要粒子加速器来烘烤饼干？”问被误导的当地妇女。',
    'News : "Fantastic Baker" set to be this year\'s most popular baby name.': '新闻：“ Fantastic Baker”将成为今年最受欢迎的婴儿名字。',
    'News : "I have seen the future," says time machine operator, "and I do not wish to go there again."': '新闻：时光机操作员说：“我已经看到了未来，而且我不想再去那里了。”',
    'News : "my upcoming album contains 3 songs about cookies", reveals celebrity.': '新闻：“我即将发行的专辑中包含3首关于Cookie的歌曲”，这表明了名人。',
    'News : "so I guess that\'s a thing now", scientist comments on cookie particles now present in virtually all steel manufactured since cookie production ramped up worldwide.': '新闻：“所以我想这就是现在了，”科学家评论说，自从全球曲奇生产迅速增长以来，几乎所有制造的钢中都存在曲奇颗粒。',
    'News : "Tomorrow\'s wealthiest people will be calculated by their worth in cookies", predict specialists.': '新闻：专家预测，“明天最富有的人将根据他们在饼干中的价值来计算”。',
    'News : "you gotta admit, all this cookie stuff is a bit ominous", says confused idiot.': '新闻：困惑的白痴说：“您必须承认，所有这些cookie东西都有点不祥。”',
    'News : all scratching tickets printed as winners, prompting national economy to crash and, against all odds, recover overnight.': '新闻：所有刮刮票都印成获奖者票，这促使国民经济崩溃，并且在万难的情况下，在一夜之间恢复过来。',
    'News : ancient baking artifacts found on distant planet; "terrifying implications", experts say.': '新闻：在遥远的星球上发现了古老的烘烤文物；专家说，“可怕的影响”。',
    'News : chocolate jewelry found fashionable, gold and diamonds "just a fad", says specialist.': '新闻：专家说，巧克力珠宝发现时尚，金色和钻石“只是一种时尚”。',
    'News : chocolate-based organisms found on distant planet!': '新闻：在遥远的星球上发现了基于巧克力的生物！',
    'News : cookie heaven allegedly "sports elevator instead of stairway"; cookie hell "paved with flagstone, as good intentions make for poor building material".': '新闻：曲奇天堂据称是“运动电梯而不是楼梯”； Cookie地狱“铺有石板，因为良好的意愿会导致不良的建筑材料”。',
    'News : cookie manufacturer completely forgoes common sense, lets strange obsession with round numbers drive building decisions!': '新闻：Cookie制造商完全放弃了常识，让对整数的奇怪痴迷驱动了建筑决策！',
    'News : cookies brought back from the past "unfit for human consumption", says historian.': '新闻：历史学家说，从过去带回来的饼干“不适合人类食用”。',
    'News : cookies now more popular than oxygen, says study.': '新闻：研究表明，饼干现在比氧气更受欢迎。',
    'News : cookies popular among all age groups, including fetuses, says study.': '新闻：研究表明，饼干在包括胎儿在内的所有年龄段人群中都很流行。',
    'News : cookies slowly creeping up their way as a competitor to traditional currency!': '新闻：Cookies逐渐成为传统货币的竞争者！',
    'News : depths of chocolate mines found to house "peculiar, chocolaty beings"!': '新闻：发现“巧克力特产”的巧克力地雷的深处！',
    'News : don\'t miss tonight\'s interview of Fantastic Baker by Blavid Bletterman!': '新闻：不要错过今晚Blavid Bletterman对Fantastic Baker的采访！',
    'News : Fantastic Baker-brand cookies "possibly more edible than competitors", says consumer survey.': '新闻：消费者调查显示，神奇的贝克品牌曲奇“可能比竞争对手可食用的多”。',
    'News : get your new charms and curses at the yearly National Spellcrafting Fair! Exclusive prices on runes and spellbooks.': '新闻：在一年一度的全国法术博览会上获得新的魅力和诅咒！符文和法术书的独家价格。',
    'News : just how extensive is the cookie pantheon? Theologians speculate about possible god of web design.': '新闻：Cookie万神殿的规模有多大？神学家推测可能是网页设计之神。',
    'News : man found dead after ingesting cookie; investigators favor "mafia snitch" hypothesis.': '新闻：一名男子在摄取饼干后发现死亡；调查人员赞成“黑手党小偷小摸”假说。',
    'News : million-to-one event sees gritty movie reboot turning out better than the original! "We have no idea how this happened", say movie execs.': '新闻：百万比一的事件显示坚韧的电影重新启动比原来的要好！电影高管说：“我们不知道这是怎么发生的。”',
    'News : nation cheers as legislators finally outlaw millenials!': '新闻：全国人民为立法者最终取缔千禧年而欢呼！',
    'News : national gold reserves dwindle as more and more of the precious mineral is turned to cookies!': '新闻：随着越来越多的珍贵矿物变成饼干，国家黄金储备正在减少！',
    'News : neighboring nation somehow elects president with sensible policies in freak accident of random chance!': '新闻：邻国以某种明智的政策选举总统，以防止偶然的偶然事件！',
    'News : new chocolate planet found, becomes target of cookie-trading spaceships!': '新闻：发现了新的巧克力星球，成为交易饼干的太空飞船的目标！',
    'News : new cookie-producing prisms linked to outbreak of rainbow-related viral videos.': '新闻：新的曲奇生产棱镜与彩虹相关的病毒视频的爆发有关。',
    'News : new popularity survey says Fantastic Baker\'s the word when it comes to cookies.': '新闻：一项新的人气调查显示，“神奇面包师”一词在Cookie方面一词。',
    'News : packs of rampaging rabbits cause billions in property damage; new strain of myxomatosis being developed.': '新闻：成堆的狂暴兔子造成数十亿美元的财产损失；正在开发一种新的粘液瘤病菌株。',
    'News : researchers conclude that what the cookie industry needs, first and foremost, is "more magnets".': '新闻：研究人员得出结论，饼干行业首先需要的是“更具吸引力”。',
    'News : strange statistical anomalies continue as weather forecast proves accurate an unprecedented 3 days in a row!': '新闻：天气预报连续三天都证明其准确无误，奇怪的统计异常现象仍在继续！',
    'News : theists of the world discover new cookie religion - "Oh boy, guess we were wrong all along!"': '新闻：世界的有神论者发现了新的cookie宗教-“哦，天哪，我们一直都是错的！”',
    'News : time machines used in unlawful time tourism!': '新闻：在非法时间旅游中使用的时间机器！',
    'News : tiny felines show sudden and amazing proficiency with fuzzy mathematics and pawlinomials, baffling scientists and pet store owners.': '新闻：小型猫科动物显示出突飞猛进的能力，他们运用模糊的数学和惯用语，困惑的科学家和宠物店老板。',
    'News : tourism to cookieverse popular with bored teenagers! Casualty rate as high as 73%!': '新闻：到无聊的青少年中受欢迎的cookieverse旅游！伤亡率高达73％！',
    'News : whole town seemingly swallowed by antimatter-induced black hole; more reliable sources affirm town "never really existed"!': '新闻：整个城镇似乎被反物质引起的黑洞吞没了；更可靠的消息来源肯定了该镇“从未真正存在”！',
    'News : alchemy-made cookies shunned by purists!': '新闻:炼金术制作的饼干被纯粹主义者所回避!',
    'News : cookie factories involved in chocolate weather controversy!': '新闻：饼干工厂卷入巧克力天气争议！',
    'News : local guru claims "there\'s a little bit of ourselves in everyone", under investigation for alleged cannibalism.': '新闻：当地宗师声称“每个人都有自己的一小部分”，因涉嫌自相残杀而受到调查。',
    'News : most bakeries now fitted with ATMs to allow for easy cookie withdrawals and deposits.': '新闻：现在，大多数面包店都配备了自动取款机，以方便提取和存放饼干。',
    'News : is another you living out their dreams in an alternate universe? Probably, you lazy bum!': '新闻:是不是另一个你在另一个世界里实现了他们的梦想?可能吧，你这个懒鬼!',
    'News : pro-diabetes movement protests against sugar-shaming. "I\'ve eaten nothing but sugar lumps for the past 13 years and I\'m feeling great!", says woman with friable skin.': '新闻：支持糖尿病的运动抗议制糖。 皮肤脆弱的女人说：“在过去的13年中，除了糖块，我什么都没吃，感觉真棒！”',
    'News : scientists warn against systematically turning light into matter - "One day, we\'ll end up with all matter and no light!"': '新闻：科学家警告不要将光系统化为物质-“有一天，我们将遇到所有物质而没有光！”',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //原样输出
    '???': '???',
    '<span style="font-size:65%;position:relative;bottom:4px;">反物质冷凝器</span>': '<span style="font-size:65%;position:relative;bottom:4px;">反物质冷凝器</span>',
    'Patreon': 'Patreon',
    'Orteil': 'Orteil',
    'QQ群号': 'QQ群号',
    'Shift': 'Shift',
    'Ctrl': 'Ctrl',
    'DashNet': 'DashNet',
    'Discord': 'Discord',
    'twitter': 'twitter',
    'tumblr': 'tumblr',
    'for': '',
    'RCP': 'RCP',
    'SLT': 'SLT',
    'SBD': 'SBD',
    'SUG': 'SUG',
    'BTR': 'BTR',
    'CHC': 'CHC',
    'CKI': 'CKI',
    'CRM': 'CRM',
    'CRL': 'CRL',
    'CNM': 'CNM',
    'HNY': 'HNY',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "• ": "• ",
    "Click to unmute ": "点击取消静音",
    "Alt cookie sound ": "Alt饼干的声音 ",
    "Alt font ": "Alt字体 ",
    "Closing warning ": "关闭警告 ",
    "CSS filters ": "CSS滤镜 ",
    "Cursors ": "游标 ",
    "Custom grandmas ": "自定义老奶奶 ",
    "Defocus ": "散焦 ",
    "Extra buttons ": "额外的按钮 ",
    "Fancy graphics ": "花哨的图形 ",
    "Fast notes ": "快速笔记 ",
    "Milk ": "牛奶 ",
    "Icon crates ": "图标箱 ",
    "Lump confirmation ": "糖块确认 ",
    "Numbers ": "数字 ",
    "Particles ": "粒子 ",
    "Short numbers ": "短数字 ",
    "Sleep mode timeout ": "睡眠模式超时 ",
    "Wobbly cookie ": "摆动饼干 ",
    "per second : ": "每秒 : ",
    "heavenly ": "天堂",
    "Heavenly ": "天堂",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    "\'s bakery": "的面包店",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^([\d\.]+) million$/,
    /^([\d\.]+) sextillion$/,
    /^([\d\.]+) trillion$/,
    /^([\d\.]+) quadrillion$/,
    /^([\d\.]+) billion$/,
    /^([\d\.]+) quintillion$/,
    /^\s*$/, //纯空格
    /^(\d+).(\d+),(\d+),(\d+),(\d+),(\d+),$/, //纯空格
    /^(\d+).(\d+),(\d+),(\d+),(\d+),$/, //纯空格
    /^(\d+).(\d+),(\d+),(\d+),$/, //纯空格
    /^(\d+).(\d+),(\d+),$/, //纯空格
    /^(\d+).(\d+),$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^(.+)Other versions\n(.+)$/, '其它版本'],
    [/^(.+) chips$/, '$1 筹码'],
    [/^(.+) cursor producing$/, '$1 游标生产'],
    [/^(.+) cursors producing$/, '$1 游标生产'],
    [/^(.+) mine producing$/, '$1 矿山生产'],
    [/^(.+) mines producing$/, '$1 矿山生产'],
    [/^(.+) factory producing$/, '$1 工厂生产'],
    [/^(.+) factories producing$/, '$1 工厂生产'],
    [/^(.+) farms producing$/, '$1 农场生产'],
    [/^(.+) farm producing$/, '$1 农场生产'],
    [/^(.+) grandma producing$/, '$1 老奶奶生产'],
    [/^(.+) grandmas producing$/, '$1 老奶奶生产'],
    [/^(.+) chancemaker producing$/, '$1 机会制造者生产'],
    [/^(.+) chancemakers producing$/, '$1 机会制造者生产'],
    [/^(.+) idleverse producing$/, '$1 闲话生产'],
    [/^(.+) idleverses producing$/, '$1 闲话生产'],
    [/^(.+) fractal engine producing$/, '$1 分形引擎生产'],
    [/^(.+) fractal engines producing$/, '$1 分形引擎生产'],
    [/^(.+) javascript console producing$/, '$1 javascript控制台生产'],
    [/^(.+) javascript consoles producing$/, '$1 javascript控制台生产'],
    [/^(.+) chancemaker producing$/, '$1 老奶奶生产'],
    [/^(.+) chancemakers producing$/, '$1 老奶奶生产'],
    [/^(.+) prism producing$/, '$1 棱镜生产'],
    [/^(.+) prisms producing$/, '$1 棱镜生产'],
    [/^(.+) time machine producing$/, '$1 时光机器生产'],
    [/^(.+) time machines producing$/, '$1 时光机器生产'],
    [/^(.+) antimatter condenser producing$/, '$1 反物质冷凝器生产'],
    [/^(.+) antimatter condensers producing$/, '$1 反物质冷凝器生产'],
    [/^(.+) wizard tower producing$/, '$1 精灵塔生产'],
    [/^(.+) wizard towers producing$/, '$1 精灵塔生产'],
    [/^(.+) portal producing$/, '$1 传送门生产'],
    [/^(.+) portals producing$/, '$1 传送门生产'],
    [/^(.+) bank producing$/, '$1 银行生产'],
    [/^(.+) banks producing$/, '$1 银行生产'],
    [/^(.+) alchemy lab producing$/, '$1 炼金术实验室生产'],
    [/^(.+) alchemy labs producing$/, '$1 炼金术实验室生产'],
    [/^(.+) temple producing$/, '$1 寺庙生产'],
    [/^(.+) temples producing$/, '$1 寺庙生产'],
    [/^(.+) shipment producing$/, '$1 装船生产'],
    [/^(.+) shipments producing$/, '$1 装船生产'],
    [/^(\d+) seconds$/, '$1 秒'],
    [/^(\d+) minutes$/, '$1 分钟'],
    [/^(\d+) hours, (\d+) minute$/, '$1 小时, $2 分钟'],
    [/^(\d+) hours, (\d+) minutes$/, '$1 小时, $2 分钟'],
    [/^(\d+) hour, (\d+) minutes$/, '$1 小时, $2 分钟'],
    [/^(\d+) hour, (\d+) minutes ago$/, '$1 小时, $2 分钟前'],
    [/^(\d+) hours, (\d+) minutes ago$/, '$1 小时, $2 分钟前'],
    [/^(\d+) minutes, (\d+) seconds$/, '$1 分钟, $2 秒'],
    [/^(.+) extra fingers granting$/, '$1 额外的手指授予'],
    [/^(\d+) grandmas$/, '$1 老奶奶'],
    [/^([\d\.,]+) more cookies$/, '$1 饼干'],
    [/^(.+)e\+(.+) more cookies$/, '$1e\+$2 饼干'],
    [/^(.+)e\+(.+) cookies$/, '$1e\+$2 饼干'],
    [/^([\d\.,]+) cookies$/, '$1 饼干'],
    [/^([\d\.]+)\% Cursor CpS$/, '$1\% 游标Cps'],
    [/^(\d+) sugar lumps$/, '$1 糖块'],
    [/^(\d+) seconds at (\d+)% CpS.$/, '$1 秒在 $2\% Cps.'],
    [/^(\d+) more notification.$/, '还有$1条通知。'],
    [/^News : (\d+) miners trapped in collapsed chocolate mine!$/, '新闻：$1名矿工被困在坍塌的巧克力矿中！'],
    [/^(\d+) times$/, '$1 次'],
    [/^(\d+) days$/, '$1 天'],
    [/^(\d+) hours$/, '$1 小时'],
    [/^CpS \+(.+)$/, '每秒点击数 \+$1'],
    [/^(\d+) days and (\d+) hours$/, '$1 天 $2 小时'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);
