//汉化杂项
var cnItems = {
    //建筑开始
    'Cursor': '游标',
    'Grandma': '老奶奶',
    'Farm': '农场',
    'Mine': '矿山',
    'Factory': '工厂',
    'Bank': '银行',
    'Temple': '寺庙',
    'Wizard tower': '精灵塔',
    'Shipment': '装船',
    'Alchemy lab': '炼金实验室',
    'Portal': '传送门',
    'Time machine': '时光机器',
    'Antimatter condenser': '反物质冷凝器',
    'Prism': '棱镜',
    'Chancemaker': '机会制造商',
    'Fractal engine': '分形引擎',
    //建筑结束
    //Tag开始
    'Upgrade': '升级',
    'Locked': '未解锁',
    'Achievement': '成就',
    'Unlocked': '已解锁',
    'Purchased': '已购买',
    'Cookie': '饼干',
    '': '',
    '': '',
    '': '',
    //Tag结束
    'clicked': '点击',
    'baked': '烘烤',
    'harvested': '收获',
    'mined': '开采',
    //升级名称开始
    'Reinforced index finger': '加强的食指',
    'Carpal tunnel prevention cream': '腕管预防霜',
    'Ambidextrous': '双手通用',
    'Thousand fingers': '千手指',
    'Million fingers': '百万手指',
    'Billion fingers': '十亿手指',
    'Trillion fingers': '万亿手指',
    'Forwards from grandma': '前锋老奶奶',
    'Steel-plated rolling pins': '钢包滚针',
    'Lubricated dentures': '润滑假牙',
    'Cheap hoes': '廉价的锄头',
    'Fertilizer': '肥料',
    'Cookie trees': '饼干树',
    'Sturdier conveyor belts': '更坚固的传送带',
    'Child labor': '童工',
    'Sweatshop': '血汗工厂',
    'Sugar gas': '糖气',
    'Megadrill': '大型钻',
    'Ultradrill': '超级钻',
    'Vanilla nebulae': '香草星云',
    'Wormholes': '虫洞',
    'Frequent flyer': '飞行常客',
    'Antimony': '锑',
    'Essence of dough': '面团的本质',
    'True chocolate': '原味巧克力',
    'Ancient tablet': '古碑文',
    'Insane oatling workers': '疯狂的燕麦工人',
    'Soul bond': '灵魂纽带',
    'Flux capacitors': '通量电容器',
    'Time paradox resolver': '时间悖论解析器',
    'Quantum conundrum': '量子难题',
    'Kitten helpers': '小猫助手',
    'Kitten workers': '小猫工人',
    'Plain cookies': '原味饼干',
    'Sugar cookies': '糖饼干',
    'Oatmeal raisin cookies': '燕麦葡萄干饼干',
    'Peanut butter cookies': '花生酱饼干',
    'Coconut cookies': '椰子饼干',
    'White chocolate cookies': '白巧克力饼干',
    'Macadamia nut cookies': '坚果饼干',
    'Double-chip cookies': '双层饼干',
    'White chocolate macadamia nut cookies': '白巧克力坚果饼干',
    'All-chocolate cookies': '全巧克力饼干',
    'Prune juice': '西梅汁',
    'Genetically-modified cookies': '转基因饼干',
    'Radium reactors': '镭反应堆',
    'Ultimadrill': '天涯钻',
    'Warp drive': '曲速驱动',
    'Ambrosia': '美味食物',
    'Sanity dance': '理智之舞',
    'Causality enforcer': '因果关系的执行者',
    'Lucky day': '幸运日',
    'Serendipity': '意外的惊喜',
    'Kitten engineers': '小猫工程师',
    'Dark chocolate-coated cookies': '黑巧克力饼干',
    'White chocolate-coated cookies': '白巧克力饼干',
    'Farmer grandmas': '农民老奶奶',
    'Miner grandmas': '矿工老奶奶',
    'Worker grandmas': '工人老奶奶',
    'Cosmic grandmas': '宇宙老奶奶',
    'Transmuted grandmas': '嬗变老奶奶',
    'Altered grandmas': '改造老奶奶',
    "Grandmas\' grandmas": '老奶奶的奶奶',
    'Specialized chocolate chips': '专业巧克力片',
    'Designer cocoa beans': '可可豆设计师',
    'Ritual rolling pins': '仪式滚针',
    'Underworld ovens': '地下烤箱',
    'One mind': '同心协力',
    'Exotic nuts': '奇异果',
    'Communal brainsweep': '集体洗脑',
    'Arcane sugar': '神秘的糖',
    'Elder Pact': '长者盟约',
    'Elder Pledge': '老人的承诺',
    'Plastic mouse': '塑料鼠标',
    'Iron mouse': '铁制鼠标',
    'Titanium mouse': '钛制鼠标',
    'Adamantium mouse': '釉质鼠标',
    'Ultrascience': '超音波',
    'Eclipse cookies': '日食饼干',
    'Zebra cookies': '斑马饼干',
    'Snickerdoodles': '肉桂奶油饼干',
    'Stroopwafels': '荷式松饼干',
    'Macaroons': '蛋白杏仁饼干',
    'Neuromancy': '神经占卜',
    'Sacrificial rolling pins': '牺牲擀面杖',
    'Get lucky': '走运',
    'Revoke Elder Covenant': '撤销老人契约',
    'Elder Covenant': '老人契约',
    'Gold hoard': '黄金储备',
    'Empire biscuits': '帝国饼干',
    'British tea biscuits': '英国茶饼干',
    'Chocolate british tea biscuits': '英国茶巧克力饼干',
    'Round british tea biscuits': '圆形英国茶饼干',
    'Round chocolate british tea biscuits': '圆巧克力英国茶饼干',
    'Round british tea biscuits with heart motif': '有心形图案的圆形英国茶饼干',
    'Round chocolate british tea biscuits with heart motif': '有心形图案的圆巧克力英国茶饼干',
    'Sugar bosons': '糖玻色子',
    'String theory': '弦理论',
    'Large macaron collider': '大马卡龙对撞机',
    'Big bang bake': '大爆炸烘烤',
    'Antigrandmas': '反物质奶奶',
    'Madeleines': '玛德琳蛋糕',
    'Palmiers': '蝴蝶酥',
    'Palets': '托盘',
    'Sabl&eacute;s': '沙琪玛饼干',
    'Kitten overseers': '小猫监工',
    'Sextillion fingers': '百万的六乘方手指',
    'Double-thick glasses': '双层厚眼镜',
    'Gingerbread scarecrows': '姜饼稻草人',
    'Recombobulators': '重新组合',
    'H-bomb mining': '氢弹开采',
    'Chocolate monoliths': '巧克力块',
    'Aqua crustulae': '甲壳纲',
    'Brane transplant': '膜移植',
    'Yestermorrow comparators': '昨天比较器',
    'Reverse cyclotrons': '反向回旋加速器',
    'Unobtainium mouse': '难得素鼠标',
    'Caramoas': '卡拉恐鸟',
    'Sagalongs': '萨松',
    'Shortfoils': '短管',
    'Win mints': '赢得薄荷糖',
    'Perfect idling': '完美的空转',
    'Fig gluttons': '无花果胶子',
    'Jaffa cakes': '佳发蛋糕',
    "Grease\'s cups": '油脂杯',
    'Loreols': '洛丽醇',
    'Heavenly chip secret': '天堂芯片的秘密',
    'Heavenly cookie stand': '天堂饼干站',
    'Heavenly bakery': '天堂面包店',
    'Heavenly confectionery': '天堂糖果店',
    'Heavenly key': '天堂钥匙',
    'Skull cookies': '骷髅饼干',
    'Ghost cookies': '幽灵饼干',
    'Bat cookies': '蝙蝠饼干',
    'Slime cookies': '粘液饼干',
    'Pumpkin cookies': '南瓜饼干',
    'Eyeball cookies': '眼球饼干',
    'Spider cookies': '蜘蛛饼干',
    'Wrinkler doormat': '皱纹门垫',
    'Persistent memory': '持久的记忆',
    'Christmas tree biscuits': '圣诞树饼干',
    'Snowflake biscuits': '雪花饼干',
    'Snowman biscuits': '雪人饼干',
    'Holly biscuits': '冬青饼干',
    'Candy cane biscuits': '糖果手杖饼干',
    'Bell biscuits': '铃铛饼干',
    'Present biscuits': '礼品饼干',
    'Gingerbread men': '姜饼人',
    'Gingerbread trees': '姜饼树',
    'A festive hat': '节庆帽子',
    'Increased merriness': '增加愉快',
    'Improved jolliness': '改良愉快',
    'A lump of coal': '一堆煤',
    'An itchy sweater': '发痒的毛衣',
    'Reindeer baking grounds': '驯鹿烘烤场',
    'Weighted sleighs': '加重雪橇',
    'Ho ho ho-flavored frosting': '何蚝味糖霜',
    'Season savings': '季节储蓄',
    'Toy workshop': '玩具车间',
    'Naughty list': '淘气名单',
    "Santa\'s bottomless bag": '圣诞老人的无底包',
    "Santa\'s helpers": '圣诞老人的助手',
    "Santa\'s legacy": '圣诞老人的遗产',
    "Santa\'s milk and cookies": '圣诞老人的牛奶和饼干',
    "Santa\'s dominion": '圣诞老人的统治',
    'Reindeer season': '驯鹿的季节',
    'Pure heart biscuits': '纯心饼干',
    'Ardent heart biscuits': '心切饼干',
    'Sour heart biscuits': '酸心饼干',
    'Weeping heart biscuits': '心水饼干',
    'Golden heart biscuits': '金心饼干',
    'Eternal heart biscuits': '永恒的心饼干',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //升级名称结束
    //成就名称开始
    'Wake and bake': '唤醒和烘烤',
    'Making some dough': '做一些面团',
    'So baked right now': '现在就烤好了',
    'Fledgling bakery': '初出茅庐的面包店',
    'Affluent bakery': '富裕的面包店',
    'World-famous bakery': '世界著名的面包店',
    'Cosmic bakery': '宇宙面包店',
    'Galactic bakery': '银河面包店',
    'Universal bakery': '万能面包店',
    'Timeless bakery': '永恒的面包店',
    'Infinite bakery': '无限的面包店',
    'Immortal bakery': '不朽的面包店',
    "Don\'t stop me now": '别拦着我',
    'You can stop now': '你可以停下来',
    'Cookies all the way down': '一路都是饼干',
    'Overdose': '过量',
    'Casual baking': '随意的烘焙',
    'Hardcore baking': '铁杆烘焙',
    'Steady tasty stream': '稳定的美味的流',
    'Cookie monster': '饼干怪兽',
    'Mass producer': '大规模生产',
    'Cookie vortex': '饼干漩涡',
    'Cookie pulsar': '饼干脉冲星',
    'Cookie quasar': '饼干类星体',
    "Oh hey, you\'re still here": '嘿，你还在这儿',
    "Let\'s never bake again": '别再烤了',
    'Sacrifice': '牺牲',
    'Oblivion': '遗忘',
    'From scratch': '从头开始',
    'Neverclick': '永不点击',
    'Clicktastic': '可以点击',
    'Clickathlon': '全能点击',
    'Clickolympics': '点击奥林匹克',
    'Clickorama': '点击奥腊马',
    'Click': '单击',
    'Double-click': '双击',
    'Mouse wheel': '鼠标滚轮',
    'Of Mice and Men': '鼠标和人',
    'The Digital': '数字',
    'Just wrong': '大错特错',
    "Grandma\'s cookies": '奶奶的饼干',
    'Sloppy kisses': '草率的吻',
    'Retirement home': '养老院',
    'My first farm': '我的第一个农场',
    'Reap what you sow': '收获你所播种',
    'Farm ill': '农场生病了',
    'Production chain': '生产链',
    'Industrial revolution': '工业革命',
    'Global warming': '全球变暖',
    'You know the drill': '你知道那个钻',
    'Excavation site': '挖掘现场',
    'Hollow the planet': '挖空地球',
    'Expedition': '探险',
    'Galactic highway': '银河高速公路',
    'Far far away': '遥远的远方',
    'Transmutation': '转化',
    'Transmogrification': '变形',
    'Gold member': '黄金会员',
    'A whole new world': '一个全新的世界',
    "Now you\'re thinking": '现在你在思考了',
    'Dimensional shift': '空间移位',
    'Time warp': '时间扭曲',
    'Alternate timeline': '交替时间线',
    'Rewriting history': '改写历史',
    'One with everything': '其中的一切',
    'Mathematician': '数学家',
    'Base 10': '基数10',
    'Golden cookie': '黄金饼干',
    'Lucky cookie': '幸运饼干',
    'A stroke of luck': '好运气',
    'Cheated cookies taste awful': '被骗的饼干味道很糟糕',
    'Uncanny clicker': '诡秘的点击器',
    'Builder': '建设者',
    'Architect': '建筑师',
    'Enhancer': '增强剂',
    'Augmenter': '增益剂',
    'Cookie-dunker': '饼干灌篮高手',
    'Fortune': '幸运',
    'True Neverclick': '真正的永不点击',
    'Elder nap': '老年小睡',
    'Elder slumber': '老年沉睡',
    'Elder': '老年人',
    'Elder calm': '平静的老人',
    'Engineer': '工程师',
    'Leprechaun': '妖精',
    "Black cat\'s paw": '黑猫的爪子',
    'Nihilism': '虚无主义',
    'Antibatter': '防糊剂',
    'Quirky quarks': '古怪夸克',
    'It does matter!': '这很重要',
    'Upgrader': '升级程序',
    'Centennial': '一百周年纪念',
    'Hardcore': '核心',
    'Speed baking I': '快速烘焙 I',
    'Speed baking II': '快速烘焙 II',
    'Speed baking III': '快速烘焙 III',
    'Getting even with the oven': '即使有烤箱',
    'Now this is pod-smashing': '这真是太棒了',
    'Chirped out': '发出叫声',
    'Follow the white rabbit': '跟着白兔',
    'Clickasmic': '点击狂魔',
    'Friend of the ancients': '老人的朋友',
    'Ruler of the ancients': '老人的统治者',
    'Wholesome': '健康',
    'Just plain lucky': '非常幸运',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //成就名称结束
    //成就名称结束
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

};

function cnItem(text) {
    //数组里面有的，返回中文
    for (var i in cnItems) {
        if (text == i) {
            return cnItems[i];
        }
    }
    //数组里面没有的，原样返回
    for (var i in cnItems) {
        if (text != i) {
            console.log("需汉化的英文Item：" + text);
            return text;
        }
    }
}



//汉化标题
var cntit = {
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',


};

function cntitle(text) {
    //数组里面有的，返回中文
    for (var i in cntit) {
        if (text == i) {
            return cntit[i];
        }
    }
    //数组里面没有的，原样返回
    for (var i in cntit) {
        if (text != i) {
            console.log("需汉化的英文标题：" + text);
            return text;
        }
    }
}
