//汉化杂项
var cnItems = {
    //建筑开始
    'Cursor': '游标',
    'cursors': '游标',
    'Grandma': '老奶奶',
    'Farm': '农场',
    'Mine': '矿山',
    'Factory': '工厂',
    'Bank': '银行',
    'Temple': '寺庙',
    'Wizard tower': '精灵塔',
    'Shipment': '装船',
    'Alchemy lab': '炼金实验室',
    'Portal': '传送门',
    'Time machine': '时光机器',
    'Antimatter condenser': '反物质冷凝器',
    'Prism': '棱镜',
    'Chancemaker': '机会制造商',
    'Fractal engine': '分形引擎',
    //建筑结束
    //Tag开始
    'Upgrade': '升级',
    'Locked': '未解锁',
    'Achievement': '成就',
    'Unlocked': '已解锁',
    'Purchased': '已购买',
    'Cookie': '饼干',
    'Heavenly': '天堂',
    'Switch': '可切换',
    'Tech': '科技',
    //Tag结束
    'clicked': '点击',
    'baked': '烘烤',
    'harvested': '收获',
    'mined': '开采',
    //升级名称开始
    'Reinforced index finger': '加强的食指',
    'Carpal tunnel prevention cream': '腕管预防霜',
    'Ambidextrous': '双手通用',
    'Thousand fingers': '千手指',
    'Million fingers': '百万手指',
    'Billion fingers': '十亿手指',
    'Trillion fingers': '万亿手指',
    'Forwards from grandma': '前锋老奶奶',
    'Steel-plated rolling pins': '钢包滚针',
    'Lubricated dentures': '润滑假牙',
    'Cheap hoes': '廉价的锄头',
    'Fertilizer': '肥料',
    'Cookie trees': '饼干树',
    'Sturdier conveyor belts': '更坚固的传送带',
    'Child labor': '童工',
    'Sweatshop': '血汗工厂',
    'Sugar gas': '糖气',
    'Megadrill': '大型钻',
    'Ultradrill': '超级钻',
    'Vanilla nebulae': '香草星云',
    'Wormholes': '虫洞',
    'Frequent flyer': '飞行常客',
    'Antimony': '锑',
    'Essence of dough': '面团的本质',
    'True chocolate': '原味巧克力',
    'Ancient tablet': '古碑文',
    'Insane oatling workers': '疯狂的燕麦工人',
    'Soul bond': '灵魂纽带',
    'Flux capacitors': '通量电容器',
    'Time paradox resolver': '时间悖论解析器',
    'Quantum conundrum': '量子难题',
    'Kitten helpers': '小猫助手',
    'Kitten workers': '小猫工人',
    'Plain cookies': '原味饼干',
    'Sugar cookies': '糖饼干',
    'Oatmeal raisin cookies': '燕麦葡萄干饼干',
    'Peanut butter cookies': '花生酱饼干',
    'Coconut cookies': '椰子饼干',
    'White chocolate cookies': '白巧克力饼干',
    'Macadamia nut cookies': '坚果饼干',
    'Double-chip cookies': '双层饼干',
    'White chocolate macadamia nut cookies': '白巧克力坚果饼干',
    'All-chocolate cookies': '全巧克力饼干',
    'Prune juice': '西梅汁',
    'Genetically-modified cookies': '转基因饼干',
    'Radium reactors': '镭反应堆',
    'Ultimadrill': '天涯钻',
    'Warp drive': '曲速驱动',
    'Ambrosia': '美味食物',
    'Sanity dance': '理智之舞',
    'Causality enforcer': '因果关系的执行者',
    'Lucky day': '幸运日',
    'Serendipity': '意外的惊喜',
    'Kitten engineers': '小猫工程师',
    'Dark chocolate-coated cookies': '黑巧克力饼干',
    'White chocolate-coated cookies': '白巧克力饼干',
    'Farmer grandmas': '农民老奶奶',
    'Miner grandmas': '矿工老奶奶',
    'Worker grandmas': '工人老奶奶',
    'Cosmic grandmas': '宇宙老奶奶',
    'Transmuted grandmas': '嬗变老奶奶',
    'Altered grandmas': '改造老奶奶',
    "Grandmas\' grandmas": '老奶奶的奶奶',
    'Specialized chocolate chips': '专业巧克力片',
    'Designer cocoa beans': '可可豆设计师',
    'Ritual rolling pins': '仪式滚针',
    'Underworld ovens': '地下烤箱',
    'One mind': '同心协力',
    'Exotic nuts': '奇异果',
    'Communal brainsweep': '集体洗脑',
    'Arcane sugar': '神秘的糖',
    'Elder Pact': '长者盟约',
    'Elder Pledge': '老人的承诺',
    'Plastic mouse': '塑料鼠标',
    'Iron mouse': '铁制鼠标',
    'Titanium mouse': '钛制鼠标',
    'Adamantium mouse': '釉质鼠标',
    'Ultrascience': '超音波',
    'Eclipse cookies': '日食饼干',
    'Zebra cookies': '斑马饼干',
    'Snickerdoodles': '肉桂奶油饼干',
    'Stroopwafels': '荷式松饼干',
    'Macaroons': '蛋白杏仁饼干',
    'Neuromancy': '神经占卜',
    'Sacrificial rolling pins': '牺牲擀面杖',
    'Get lucky': '走运',
    'Revoke Elder Covenant': '撤销老人契约',
    'Elder Covenant': '老人契约',
    'Gold hoard': '黄金储备',
    'Empire biscuits': '帝国饼干',
    'British tea biscuits': '英国茶饼干',
    'Chocolate british tea biscuits': '英国茶巧克力饼干',
    'Round british tea biscuits': '圆形英国茶饼干',
    'Round chocolate british tea biscuits': '圆巧克力英国茶饼干',
    'Round british tea biscuits with heart motif': '有心形图案的圆形英国茶饼干',
    'Round chocolate british tea biscuits with heart motif': '有心形图案的圆巧克力英国茶饼干',
    'Sugar bosons': '糖玻色子',
    'String theory': '弦理论',
    'Large macaron collider': '大马卡龙对撞机',
    'Big bang bake': '大爆炸烘烤',
    'Antigrandmas': '反物质奶奶',
    'Madeleines': '玛德琳蛋糕',
    'Palmiers': '蝴蝶酥',
    'Palets': '托盘',
    'Sabl&eacute;s': '沙琪玛饼干',
    'Kitten overseers': '小猫监工',
    'Sextillion fingers': '百万的六乘方手指',
    'Double-thick glasses': '双层厚眼镜',
    'Gingerbread scarecrows': '姜饼稻草人',
    'Recombobulators': '重新组合',
    'H-bomb mining': '氢弹开采',
    'Chocolate monoliths': '巧克力块',
    'Aqua crustulae': '甲壳纲',
    'Brane transplant': '膜移植',
    'Yestermorrow comparators': '昨天比较器',
    'Reverse cyclotrons': '反向回旋加速器',
    'Unobtainium mouse': '难得素鼠标',
    'Caramoas': '卡拉恐鸟',
    'Sagalongs': '萨松',
    'Shortfoils': '短管',
    'Win mints': '赢得薄荷糖',
    'Perfect idling': '完美的空转',
    'Fig gluttons': '无花果胶子',
    'Jaffa cakes': '佳发蛋糕',
    "Grease\'s cups": '油脂杯',
    'Loreols': '洛丽醇',
    'Heavenly chip secret': '天堂芯片的秘密',
    'Heavenly cookie stand': '天堂饼干站',
    'Heavenly bakery': '天堂面包店',
    'Heavenly confectionery': '天堂糖果店',
    'Heavenly key': '天堂钥匙',
    'Skull cookies': '骷髅饼干',
    'Ghost cookies': '幽灵饼干',
    'Bat cookies': '蝙蝠饼干',
    'Slime cookies': '粘液饼干',
    'Pumpkin cookies': '南瓜饼干',
    'Eyeball cookies': '眼球饼干',
    'Spider cookies': '蜘蛛饼干',
    'Wrinkler doormat': '皱纹门垫',
    'Persistent memory': '持久的记忆',
    'Christmas tree biscuits': '圣诞树饼干',
    'Snowflake biscuits': '雪花饼干',
    'Snowman biscuits': '雪人饼干',
    'Holly biscuits': '冬青饼干',
    'Candy cane biscuits': '糖果手杖饼干',
    'Bell biscuits': '铃铛饼干',
    'Present biscuits': '礼品饼干',
    'Gingerbread men': '姜饼人',
    'Gingerbread trees': '姜饼树',
    'A festive hat': '节庆帽子',
    'Increased merriness': '增加愉快',
    'Improved jolliness': '改良愉快',
    'A lump of coal': '一堆煤',
    'An itchy sweater': '发痒的毛衣',
    'Reindeer baking grounds': '驯鹿烘烤场',
    'Weighted sleighs': '加重雪橇',
    'Ho ho ho-flavored frosting': '何蚝味糖霜',
    'Season savings': '季节储蓄',
    'Toy workshop': '玩具车间',
    'Naughty list': '淘气名单',
    "Santa\'s bottomless bag": '圣诞老人的无底包',
    "Santa\'s helpers": '圣诞老人的助手',
    "Santa\'s legacy": '圣诞老人的遗产',
    "Santa\'s milk and cookies": '圣诞老人的牛奶和饼干',
    "Santa\'s dominion": '圣诞老人的统治',
    'Reindeer season': '驯鹿的季节',
    'Pure heart biscuits': '纯心饼干',
    'Ardent heart biscuits': '心切饼干',
    'Sour heart biscuits': '酸心饼干',
    'Weeping heart biscuits': '心水饼干',
    'Golden heart biscuits': '金心饼干',
    'Eternal heart biscuits': '永恒的心饼干',
    'Gem polish': '宝石抛光',
    '9th color': '9号颜色',
    'Chocolate light': '巧克力之光',
    'Grainbow': '谷粒弓',
    'Pure cosmic light': '纯粹的宇宙之光',
    'Rainbow grandmas': '彩虹老奶奶',
    'Season switcher': '季节切换器',
    'Festive biscuit': '节日饼干',
    'Ghostly biscuit': '幽灵饼干',
    'Lovesick biscuit': '相思病饼干',
    'Fool\'s biscuit': '傻瓜的饼干',
    'Eternal seasons': '永恒的季节',
    'Kitten managers': '小猫经理',
    'Septillion fingers': '巨量的手指',
    'Octillion fingers': '千的九次方手指',
    'Eludium mouse': 'E合金鼠标',
    'Wishalloy mouse': '叉合金鼠标',
    'Aging agents': '老化剂',
    'Pulsar sprinklers': '脉冲星洒水器',
    'Deep-bake process': '深度烘焙过程',
    'Coreforge': '铁匠铺',
    'Generation ship': '发电船',
    'Origin crucible': '起源坩埚',
    'Deity-sized portals': '大型传送门',
    'Far future enactment': '未来的法令',
    'Nanocosmics': '纳米宇宙',
    'Glow-in-the-dark': '在黑暗中发光',
    'Rose macarons': '玫瑰马卡龙',
    'Lemon macarons': '柠檬马卡龙',
    'Chocolate macarons': '巧克力马卡龙',
    'Pistachio macarons': '开心果马卡龙',
    'Hazelnut macarons': '榛子马卡龙',
    'Violet macarons': '紫罗兰马卡龙',
    'Magic shenanigans': '神奇的恶作剧',
    'Bunny biscuit': '兔子饼干',
    'Chicken egg': '鸡蛋',
    'Duck egg': '鸭蛋',
    'Turkey egg': '火鸡蛋',
    'Quail egg': '鹌鹑蛋',
    'Robin egg': '知更鸟蛋',
    'Ostrich egg': '鸵鸟蛋',
    'Cassowary egg': '食火鸡蛋',
    'Salmon roe': '鲑鱼籽',
    'Frogspawn': '蛙卵',
    'Shark egg': '鲨鱼卵',
    'Turtle egg': '龟蛋',
    'Ant larva': '蚂蚁幼虫',
    'Golden goose egg': '金鹅蛋',
    'Faberge egg': '法贝热彩蛋',
    'Wrinklerspawn': '皱纹卵',
    'Cookie egg': '饼干蛋',
    'Omelette': '煎蛋',
    'Chocolate egg': '巧克力蛋',
    'Century egg': '世纪蛋',
    '"egg"': '"蛋"',
    'Walnut cookies': '核桃饼干',
    'Hazelnut cookies': '榛子饼干',
    'Almond cookies': '杏仁饼干',
    'Label printer': '标签打印机',
    'Good manners': '礼貌',
    'Lindworms': '林德蠕虫',
    'Armythril mouse': '阿迈斯里鼠标',
    'Reverse dementia': '反向痴呆症',
    'Humane pesticides': '人道杀虫剂',
    'Mole people': '鼹鼠人',
    'Machine learning': '机器学习',
    'Edible money': '可食用货币',
    'Sick rap prayers': '饶舌祈祷者',
    'Deluxe tailored wands': '豪华定制魔杖',
    'Autopilot': '自动驾驶仪',
    'The advent of chemistry': '化学的出现',
    'The real world': '真实的世界',
    'Second seconds': '第二秒',
    'Quantum comb': '量子梳',
    'Crystal mirrors': '水晶镜子',
    'Bunnypedes': '小松鼠',
    'Kitten assistants to the regional manager': '小猫助理区域经理',
    'Charm quarks': '魅力夸克',
    'Pink biscuits': '粉色饼干',
    'Whole-grain cookies': '全麦饼干',
    'Candy cookies': '糖果饼干',
    'Big chip cookies': '大曲奇饼',
    'One chip cookies': '一个曲奇饼',
    'Sugar baking': '糖烘焙',
    'Sugar craving': '糖分渴求',
    'Sugar aging process': '糖老化过程',
    'Sugar frenzy': '糖的狂热',
    'Sprinkles cookies': '小甜饼',
    'Golden switch': '黄金开关',
    'Classic dairy selection': '选择经典的乳制品',
    'Fanciful dairy selection': '奇特的乳制品选择',
    'Dragon cookie': '龙形饼干',
    'Tin of butter cookies': '奶油饼干罐头',
    'Chimera': '奇美拉',
    'A crumbly egg': '易碎的鸡蛋',
    'How to bake your dragon': '如何烤你的龙',
    'Kitten accountants': '小猫会计',
    'Kitten specialists': '小猫专家',
    'Kitten experts': '小猫能手',
    'Reverse shadows': '反向阴影',
    'The Unbridling': '未被发现的',
    'Wheat triffids': '小麦的由来',
    'Canola oil wells': '菜籽油井',
    '78-hour days': '每天78小时',
    'The stuff rationale': '基本原理',
    'Theocracy': '神权政治',
    'Rabbit trick': '兔子戏法',
    'The final frontier': '最后的边界',
    'Beige goo': '原色古果',
    'Maddening chants': '疯狂的圣歌',
    'Cookietopian moments of maybe': '也许是小饼干的时候',
    'Some other super-tiny fundamental particle? Probably?': '还有其他超微小的基本粒子吗？',
    'Turbo-charged soil': '涡轮增压土壤',
    'Technobsidian mouse': '高科技鼠标',
    'Kitten marketeers': '小猫市场商人',
    'Festivity loops': '节日循环',
    'Persian rice cookies': '波斯米饼干',
    'Pure black chocolate cookies': '纯黑巧克力饼干',
    'Pure white chocolate cookies': '纯白巧克力饼干',
    'Ladyfingers': '松脆饼',
    'Tuiles': '瓦片',
    'Chocolate-stuffed biscuits': '巧克力饼干',
    'Checker cookies': '切克饼干',
    'Butter cookies': '黄油饼干',
    'Cream cookies': '奶油饼干',
    'Quantum electronics': '量子电子学',
    'Asteroid mining': '小行星采矿',
    'Seismic magic': '地震魔法',
    'Rain prayer': '雨中的祈祷',
    'Future almanacs': '未来年鉴',
    'Temporal overclocking': '颞超频',
    'Contracts from beyond': '来自远方的合同',
    'Printing presses': '印刷机',
    'Paganism': '异教',
    'God particle': '上帝粒子',
    'Arcane knowledge': '奥术知识',
    'Magical botany': '神奇植物学',
    'Fossil fuels': '化石燃料',
    'Shipyards': '船厂',
    'Primordial ores': '原始矿石',
    'Gold fund': '黄金基金',
    'Infernal crops': '地狱作物',
    'Abysmal glimmer': '暗淡的微光',
    'Relativistic parsec-skipping': '相对论性的省略',
    'Primeval glow': '原始辉光',
    'Extra physics funding': '额外的物理资金',
    'Chemical proficiency': '化学能力',
    'Light magic': '光明魔法',
    'Mystical energies': '神秘的能量',
    'Synergies Vol. I': '协同效应 I',
    'Synergies Vol. II': '协同效应 II',
    'Golden switch [off]': '黄金开关[关闭]',
    'Golden switch [on]': '黄金开关[开启]',
    'Milk selector': '牛奶选择器',
    'Automatic': '自动',
    'Plain milk': '纯牛奶',
    'Chocolate milk': '巧克力牛奶',
    'Raspberry milk': '树莓牛奶',
    'Orange milk': '橙汁牛奶',
    'Caramel milk': '焦糖牛奶',
    'Banana milk': '香蕉牛奶',
    'Lime milk': '石灰牛奶',
    'Blueberry milk': '蓝莓牛奶',
    'Strawberry milk': '草莓牛奶',
    'Vanilla milk': '香草牛奶',
    'Honey milk': '蜂蜜牛奶',
    'Coffee milk': '咖啡牛奶',
    'Tea milk': '加茶牛奶',
    'Coconut milk': '椰子牛奶',
    'Cherry milk': '樱桃牛奶',
    'Spiced milk': '五香牛奶',
    'Maple milk': '枫糖牛奶',
    'Zebra milk': '斑马牛奶',
    'Cosmic milk': '宇宙牛奶',
    'Flaming milk': '火红的牛奶',
    'Sanguine milk': '血红色的牛奶',
    'Midas milk': '迈达斯牛奶',
    'Midnight milk': '午夜牛奶',
    'Green inferno milk': '绿色地狱牛奶',
    'Frostfire milk': '霜火牛奶',
    'Soy milk': '豆奶',
    'Enlarged pantheon': '扩大万神殿',
    'Sun festival': '太阳节',
    'Delicious blessing': '美味的祝福',
    'Sacrifices': '牺牲',
    'Golden idols': '金色偶像',
    'Financial zen': '金融禅宗',
    'Exponential interest rates': '指数利率',
    'Chocolate coins': '巧克力硬币',
    'Acid-proof vaults': '耐酸金库',
    'Scissor-resistant credit cards': '抗剪刀的信用卡',
    'Taller tellers': '更高级的出纳员',
    'Caramel macarons': '焦糖马卡龙',
    'Licorice macarons': '甘草马卡龙',
    'Great Baker in the sky': '天上的面包师',
    'Pointier hats': '尖尖的帽子',
    'Beardlier beards': '胡子胡子',
    'Ancient grimoires': '古魔典',
    'Kitchen curses': '厨房诅咒',
    'School of sorcery': '魔法学校',
    'Dark formulas': '黑暗公式',
    'Banker grandmas': '银行家老奶奶',
    'Priestess grandmas': '祭司老奶奶',
    'Witch grandmas': '女巫老奶奶',
    '': '',
    '': '',
    '': '',
    //升级名称结束
    //成就名称开始
    'Wake and bake': '唤醒和烘烤',
    'Making some dough': '做一些面团',
    'So baked right now': '现在就烤好了',
    'Fledgling bakery': '初出茅庐的面包店',
    'Affluent bakery': '富裕的面包店',
    'World-famous bakery': '世界著名的面包店',
    'Cosmic bakery': '宇宙面包店',
    'Galactic bakery': '银河面包店',
    'Universal bakery': '万能面包店',
    'Timeless bakery': '永恒的面包店',
    'Infinite bakery': '无限的面包店',
    'Immortal bakery': '不朽的面包店',
    "Don\'t stop me now": '别拦着我',
    'You can stop now': '你可以停下来',
    'Cookies all the way down': '一路都是饼干',
    'Overdose': '过量',
    'Casual baking': '随意的烘焙',
    'Hardcore baking': '铁杆烘焙',
    'Steady tasty stream': '稳定的美味的流',
    'Cookie monster': '饼干怪兽',
    'Mass producer': '大规模生产',
    'Cookie vortex': '饼干漩涡',
    'Cookie pulsar': '饼干脉冲星',
    'Cookie quasar': '饼干类星体',
    "Oh hey, you\'re still here": '嘿，你还在这儿',
    "Let\'s never bake again": '别再烤了',
    'Sacrifice': '牺牲',
    'Oblivion': '遗忘',
    'From scratch': '从头开始',
    'Neverclick': '永不点击',
    'Clicktastic': '可以点击',
    'Clickathlon': '全能点击',
    'Clickolympics': '点击奥林匹克',
    'Clickorama': '点击奥腊马',
    'Click': '单击',
    'Double-click': '双击',
    'Mouse wheel': '鼠标滚轮',
    'Of Mice and Men': '鼠标和人',
    'The Digital': '数字',
    'Just wrong': '大错特错',
    "Grandma\'s cookies": '奶奶的饼干',
    'Sloppy kisses': '草率的吻',
    'Retirement home': '养老院',
    'My first farm': '我的第一个农场',
    'Reap what you sow': '收获你所播种',
    'Farm ill': '农场生病了',
    'Production chain': '生产链',
    'Industrial revolution': '工业革命',
    'Global warming': '全球变暖',
    'You know the drill': '你知道那个钻',
    'Excavation site': '挖掘现场',
    'Hollow the planet': '挖空地球',
    'Expedition': '探险',
    'Galactic highway': '银河高速公路',
    'Far far away': '遥远的远方',
    'Transmutation': '转化',
    'Transmogrification': '变形',
    'Gold member': '黄金会员',
    'A whole new world': '一个全新的世界',
    "Now you\'re thinking": '现在你在思考了',
    'Dimensional shift': '空间移位',
    'Time warp': '时间扭曲',
    'Alternate timeline': '交替时间线',
    'Rewriting history': '改写历史',
    'One with everything': '其中的一切',
    'Mathematician': '数学家',
    'Base 10': '基数10',
    'Golden cookie': '黄金饼干',
    'Lucky cookie': '幸运饼干',
    'A stroke of luck': '好运气',
    'Cheated cookies taste awful': '被骗的饼干味道很糟糕',
    'Uncanny clicker': '诡秘的点击器',
    'Builder': '建设者',
    'Architect': '建筑师',
    'Enhancer': '增强剂',
    'Augmenter': '增益剂',
    'Cookie-dunker': '饼干灌篮高手',
    'Fortune': '幸运',
    'True Neverclick': '真正的永不点击',
    'Elder nap': '老年小睡',
    'Elder slumber': '老年沉睡',
    'Elder': '老年人',
    'Elder calm': '平静的老人',
    'Engineer': '工程师',
    'Leprechaun': '妖精',
    "Black cat\'s paw": '黑猫的爪子',
    'Nihilism': '虚无主义',
    'Antibatter': '防糊剂',
    'Quirky quarks': '古怪夸克',
    'It does matter!': '这很重要',
    'Upgrader': '升级程序',
    'Centennial': '一百周年纪念',
    'Hardcore': '核心',
    'Speed baking I': '快速烘焙 I',
    'Speed baking II': '快速烘焙 II',
    'Speed baking III': '快速烘焙 III',
    'Getting even with the oven': '即使有烤箱',
    'Now this is pod-smashing': '这真是太棒了',
    'Chirped out': '发出叫声',
    'Follow the white rabbit': '跟着白兔',
    'Clickasmic': '点击狂魔',
    'Friend of the ancients': '老人的朋友',
    'Ruler of the ancients': '老人的统治者',
    'Wholesome': '健康',
    'Just plain lucky': '非常幸运',
    'You get nothing': '你什么都没有得到',
    '[X] extra fingers': '[X] 额外的手指',
    'Kitten consultants': '小猫顾问',
    'Self-contained': '自包含',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //成就名称结束
    //天赋名称开始
    'Legacy': '遗产',
    'Basic wallpaper assortment': '基本壁纸分类',
    'Elder spice': '老香料',
    'Residual luck': '残余运气',
    'Fantasteel mouse': '范塔钢鼠标',
    'Nevercrack mouse': '永不崩溃的鼠标',
    'Five-finger discount': '五指折扣',
    'Box of brand biscuits': '品牌饼干盒',
    'Box of macarons': '马卡龙盒子',
    'Tin of british tea biscuits': '一罐英国茶饼干',
    'Starspawn': '星卵',
    'Starsnow': '星雪',
    'Starterror': '星际恐怖',
    'Starlove': '星际之恋',
    'Startrade': '星际贸易',
    'Angels': '天使',
    'Archangels': '大天使',
    'Virtues': '美德',
    'Dominions': '领地',
    'Cherubim': '智天使',
    'Seraphim': '六翼天使',
    'God': '上帝',
    'Twin Gates of Transcendence': '双重超越之门',
    'Heavenly luck': '天上的运气',
    'Lasting fortune': '永恒的财富',
    'Decisive fate': '决定性的命运',
    'Divine discount': '神圣折扣',
    'Divine sales': '神圣销售',
    'Divine bakeries': '神圣的面包店',
    'Starter kit': '启动装置',
    'Starter kitchen': '启动厨房',
    'Halo gloves': '光环手套',
    'Kitten angels': '小猫天使',
    'Unholy bait': '邪恶的诱饵',
    'Sacrilegious corruption': '亵渎神明',
    'Xtreme walkers': '播放器步行者',
    'Permanent upgrade slot I': '永久升级槽 I',
    'Permanent upgrade slot II': '永久升级槽 II',
    'Permanent upgrade slot III': '永久升级槽 III',
    'Permanent upgrade slot IV': '永久升级槽 IV',
    'Permanent upgrade slot V': '永久升级槽 V',
    'Permanent upgrade slot VI': '永久升级槽 VI',
    'Heavenly cookies': '天堂饼干',
    'Wrinkly cookies': '皱纹饼干',
    'Distilled essence of redoubled luck': '翻倍运气的精华',
    'Occult obstruction': '神秘障碍',
    'Glucose-charged air': '葡萄糖空气',
    'Lavender chocolate butter biscuit': '薰衣草巧克力奶油饼干',
    'Lombardia cookies': '伦巴第饼干',
    'Bastenaken cookies': '巴斯顿坎饼干',
    'Pecan sandies': '山核桃饼干',
    'Moravian spice cookies': '摩拉维亚香料饼干',
    'Anzac biscuits': '澳扎克饼干',
    'Buttercakes': '黄油蛋糕',
    'Ice cream sandwiches': '冰淇淋三明治',
    'Stevia Caelestis': '甜菊糖',
    'Diabetica Daemonicus': '糖尿病患者',
    'Sucralosia Inutilis': '舒张症',
    'Lucky digit': '幸运数字',
    'Lucky number': '幸运数',
    'Lucky payout': '幸运的支付',
    'Background selector': '背景选择器',
    'Lucky grandmas': '幸运老奶奶',
    'Keepsakes': '纪念品',
    'Golden cookie alert sound': '金色饼干警报声',
    'Inspired checklist': '灵感清单',
    'Purrchased': '购买',
    'Abaddon': '阿巴登',
    'Heralds': '使者',
    'Belphegor': '贝尔菲格',
    'Mammon': '财神',
    'Satan': '撒旦',
    'Asmodeus': '魔王',
    'Beelzebub': '恶魔',
    'Lucifer': '路西法',
    'Golden cookie sound selector': '黄金饼干声音选择器',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //天赋名称结束
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //原样输出
    '???': '???',
    '<span style="font-size:65%;position:relative;bottom:4px;">反物质冷凝器</span>': '<span style="font-size:65%;position:relative;bottom:4px;">反物质冷凝器</span>',

};

function cnItem(text) {
    //数组里面有的，返回中文
    for (var i in cnItems) {
        if (text == i) {
            return cnItems[i];
        }
    }
    //数组里面没有的，原样返回
    for (var i in cnItems) {
        if (text != i) {
            console.log("需汉化的英文Item：" + text);
            return text;
        }
    }
}



//汉化标题
var cntit = {
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',


};

function cntitle(text) {
    //数组里面有的，返回中文
    for (var i in cntit) {
        if (text == i) {
            return cntit[i];
        }
    }
    //数组里面没有的，原样返回
    for (var i in cntit) {
        if (text != i) {
            console.log("需汉化的英文标题：" + text);
            return text;
        }
    }
}
